"""
Slack Capability Registry
"""

from app.connectors.slack import SlackConnector

slack_connector = SlackConnector()

_DELEGATION = {
    "credential_type": "agent",
    "supports_delegation": True,
    "delegation_instructions": "Add Aleq bot to your Slack workspace",
}

SLACK_CAPABILITIES = {
    "message.send": {
        "handler": slack_connector.send_message,
        "tool_name": "slack.send_message",
        "description": "Send a message to a Slack channel",
        "requires_oauth": True,
        "service": "slack",
        **_DELEGATION,
    },
    "message.direct": {
        "handler": slack_connector.send_direct_message,
        "tool_name": "slack.send_direct_message",
        "description": "Send a direct message on Slack",
        "requires_oauth": True,
        "service": "slack",
        **_DELEGATION,
    },
    "message.update": {
        "handler": slack_connector.update_message,
        "tool_name": "slack.update_message",
        "description": "Update (edit) a message in Slack",
        "requires_oauth": True,
        "service": "slack",
        **_DELEGATION,
    },
    "message.delete": {
        "handler": slack_connector.delete_message,
        "tool_name": "slack.delete_message",
        "description": "Delete a message in Slack",
        "requires_oauth": True,
        "service": "slack",
        **_DELEGATION,
    },
    "message.pin": {
        "handler": slack_connector.pin_message,
        "tool_name": "slack.pin_message",
        "description": "Pin a message to a channel",
        "requires_oauth": True,
        "service": "slack",
        **_DELEGATION,
    },
    "message.unpin": {
        "handler": slack_connector.unpin_message,
        "tool_name": "slack.unpin_message",
        "description": "Unpin a message from a channel",
        "requires_oauth": True,
        "service": "slack",
        **_DELEGATION,
    },
    "message.schedule": {
        "handler": slack_connector.schedule_message,
        "tool_name": "slack.schedule_message",
        "description": "Schedule a message for future delivery",
        "requires_oauth": True,
        "service": "slack",
        **_DELEGATION,
    },
    "thread.replies": {
        "handler": slack_connector.get_thread_replies,
        "tool_name": "slack.get_thread_replies",
        "description": "Get replies in a message thread",
        "requires_oauth": True,
        "service": "slack",
        **_DELEGATION,
    },
    "file.upload": {
        "handler": slack_connector.upload_file,
        "tool_name": "slack.upload_file",
        "description": "Upload a file to Slack",
        "requires_oauth": True,
        "service": "slack",
        **_DELEGATION,
    },
    "channel.create": {
        "handler": slack_connector.create_channel,
        "tool_name": "slack.create_channel",
        "description": "Create a Slack channel",
        "requires_oauth": True,
        "service": "slack",
        **_DELEGATION,
    },
    "channel.invite": {
        "handler": slack_connector.invite_to_channel,
        "tool_name": "slack.invite_to_channel",
        "description": "Invite users to a Slack channel",
        "requires_oauth": True,
        "service": "slack",
        **_DELEGATION,
    },
    "channel.history": {
        "handler": slack_connector.get_channel_history,
        "tool_name": "slack.get_channel_history",
        "description": "Get message history from a Slack channel",
        "requires_oauth": True,
        "service": "slack",
        **_DELEGATION,
    },
    "channel.list": {
        "handler": slack_connector.list_channels,
        "tool_name": "slack.list_channels",
        "description": "List all channels in the workspace",
        "requires_oauth": True,
        "service": "slack",
        **_DELEGATION,
    },
    "channel.info": {
        "handler": slack_connector.get_channel_info,
        "tool_name": "slack.get_channel_info",
        "description": "Get detailed information about a channel",
        "requires_oauth": True,
        "service": "slack",
        **_DELEGATION,
    },
    "channel.archive": {
        "handler": slack_connector.archive_channel,
        "tool_name": "slack.archive_channel",
        "description": "Archive a Slack channel",
        "requires_oauth": True,
        "service": "slack",
        **_DELEGATION,
    },
    "channel.topic": {
        "handler": slack_connector.set_channel_topic,
        "tool_name": "slack.set_channel_topic",
        "description": "Set the topic for a Slack channel",
        "requires_oauth": True,
        "service": "slack",
        **_DELEGATION,
    },
    "channel.purpose": {
        "handler": slack_connector.set_channel_purpose,
        "tool_name": "slack.set_channel_purpose",
        "description": "Set the purpose for a Slack channel",
        "requires_oauth": True,
        "service": "slack",
        **_DELEGATION,
    },
    "reaction.add": {
        "handler": slack_connector.add_reaction,
        "tool_name": "slack.add_reaction",
        "description": "Add a reaction to a message",
        "requires_oauth": True,
        "service": "slack",
        **_DELEGATION,
    },
    "reaction.remove": {
        "handler": slack_connector.remove_reaction,
        "tool_name": "slack.remove_reaction",
        "description": "Remove a reaction from a message",
        "requires_oauth": True,
        "service": "slack",
        **_DELEGATION,
    },
    "user.list": {
        "handler": slack_connector.list_users,
        "tool_name": "slack.list_users",
        "description": "List all users in the workspace",
        "requires_oauth": True,
        "service": "slack",
        **_DELEGATION,
    },
    "user.info": {
        "handler": slack_connector.get_user_info,
        "tool_name": "slack.get_user_info",
        "description": "Get detailed information about a user",
        "requires_oauth": True,
        "service": "slack",
        **_DELEGATION,
    },
    "search.messages": {
        "handler": slack_connector.search_messages,
        "tool_name": "slack.search_messages",
        "description": "Search for messages in the workspace",
        "requires_oauth": True,
        "service": "slack",
        **_DELEGATION,
    },
}
