"""
Google Workspace Capability Registry
Google Drive, Google Calendar, Google Sheets
"""

from app.connectors.google_calendar import GoogleCalendarConnector
from app.connectors.google_drive import GoogleDriveConnector
from app.connectors.google_sheets import GoogleSheetsConnector

# Initialize connectors
gdrive_connector = GoogleDriveConnector()
gcal_connector = GoogleCalendarConnector()
gsheets_connector = GoogleSheetsConnector()

GOOGLE_CAPABILITIES = {
    # ========== GOOGLE DRIVE ==========
    "gdrive.file.upload": {
        "handler": gdrive_connector.upload_file,
        "tool_name": "google_drive.upload_file",
        "description": "Upload file to Google Drive",
        "requires_oauth": True,
        "service": "google",
        "credential_type": "agent",
        "supports_delegation": True,
        "delegation_instructions": "Grant Aleq access to your Google Drive",
    },
    "gdrive.file.download": {
        "handler": gdrive_connector.download_file,
        "tool_name": "google_drive.download_file",
        "description": "Download file from Google Drive",
        "requires_oauth": True,
        "service": "google",
        "credential_type": "agent",
        "supports_delegation": True,
        "delegation_instructions": "Grant Aleq access to your Google Drive",
    },
    "gdrive.file.list": {
        "handler": gdrive_connector.list_files,
        "tool_name": "google_drive.list_files",
        "description": "List files in Google Drive folder",
        "requires_oauth": True,
        "service": "google",
        "credential_type": "agent",
        "supports_delegation": True,
        "delegation_instructions": "Grant Aleq access to your Google Drive",
    },
    "gdrive.folder.create": {
        "handler": gdrive_connector.create_folder,
        "tool_name": "google_drive.create_folder",
        "description": "Create folder in Google Drive",
        "requires_oauth": True,
        "service": "google",
        "credential_type": "agent",
        "supports_delegation": True,
        "delegation_instructions": "Grant Aleq access to your Google Drive",
    },
    "gdrive.file.metadata": {
        "handler": gdrive_connector.get_file_metadata,
        "tool_name": "google_drive.get_file_metadata",
        "description": "Get file metadata from Google Drive",
        "requires_oauth": True,
        "service": "google",
        "credential_type": "agent",
        "supports_delegation": True,
        "delegation_instructions": "Grant Aleq access to your Google Drive",
    },
    "gdrive.file.delete": {
        "handler": gdrive_connector.delete_file,
        "tool_name": "google_drive.delete_file",
        "description": "Delete a file from Google Drive",
        "requires_oauth": True,
        "service": "google",
        "credential_type": "agent",
        "supports_delegation": True,
        "delegation_instructions": "Grant Aleq access to your Google Drive",
    },
    "gdrive.file.search": {
        "handler": gdrive_connector.search_files,
        "tool_name": "google_drive.search_files",
        "description": "Search for files in Google Drive",
        "requires_oauth": True,
        "service": "google",
        "credential_type": "agent",
        "supports_delegation": True,
        "delegation_instructions": "Grant Aleq access to your Google Drive",
    },
    # ========== GOOGLE CALENDAR ==========
    "gcal.event.create": {
        "handler": gcal_connector.create_event,
        "tool_name": "google_calendar.create_event",
        "description": "Create calendar event in Google Calendar",
        "requires_oauth": True,
        "service": "google",
        "credential_type": "agent",
        "supports_delegation": True,
        "delegation_instructions": "Grant Aleq access to your Google Calendar",
    },
    "gcal.availability.check": {
        "handler": gcal_connector.check_availability,
        "tool_name": "google_calendar.check_availability",
        "description": "Check free/busy time for attendees in Google Calendar",
        "requires_oauth": True,
        "service": "google",
        "credential_type": "agent",
        "supports_delegation": True,
        "delegation_instructions": "Grant Aleq access to your Google Calendar",
    },
    "gcal.event.update": {
        "handler": gcal_connector.update_event,
        "tool_name": "google_calendar.update_event",
        "description": "Update calendar event in Google Calendar",
        "requires_oauth": True,
        "service": "google",
        "credential_type": "agent",
        "supports_delegation": True,
        "delegation_instructions": "Grant Aleq access to your Google Calendar",
    },
    "gcal.event.list": {
        "handler": gcal_connector.list_events,
        "tool_name": "google_calendar.list_events",
        "description": "List calendar events in Google Calendar",
        "requires_oauth": True,
        "service": "google",
        "credential_type": "agent",
        "supports_delegation": True,
        "delegation_instructions": "Grant Aleq access to your Google Calendar",
    },
    "gcal.event.cancel": {
        "handler": gcal_connector.cancel_event,
        "tool_name": "google_calendar.cancel_event",
        "description": "Cancel calendar event in Google Calendar",
        "requires_oauth": True,
        "service": "google",
        "credential_type": "agent",
        "supports_delegation": True,
        "delegation_instructions": "Grant Aleq access to your Google Calendar",
    },
    "gcal.event.get": {
        "handler": gcal_connector.get_event,
        "tool_name": "google_calendar.get_event",
        "description": "Get a single calendar event from Google Calendar",
        "requires_oauth": True,
        "service": "google",
        "credential_type": "agent",
        "supports_delegation": True,
        "delegation_instructions": "Grant Aleq access to your Google Calendar",
    },
    "gcal.calendar.list": {
        "handler": gcal_connector.list_calendars,
        "tool_name": "google_calendar.list_calendars",
        "description": "List user's calendars in Google Calendar",
        "requires_oauth": True,
        "service": "google",
        "credential_type": "agent",
        "supports_delegation": True,
        "delegation_instructions": "Grant Aleq access to your Google Calendar",
    },
    # ========== GOOGLE SHEETS ==========
    "gsheets.range.get": {
        "handler": gsheets_connector.get_range,
        "tool_name": "google_sheets.get_range",
        "description": "Get values from range in Google Sheets",
        "requires_oauth": True,
        "service": "google",
        "credential_type": "agent",
        "supports_delegation": True,
        "delegation_instructions": "Grant Aleq access to your Google Sheets",
    },
    "gsheets.range.update": {
        "handler": gsheets_connector.update_range,
        "tool_name": "google_sheets.update_range",
        "description": "Update values in range in Google Sheets",
        "requires_oauth": True,
        "service": "google",
        "credential_type": "agent",
        "supports_delegation": True,
        "delegation_instructions": "Grant Aleq access to your Google Sheets",
    },
    "gsheets.row.append": {
        "handler": gsheets_connector.append_row,
        "tool_name": "google_sheets.append_row",
        "description": "Append row to Google Sheets",
        "requires_oauth": True,
        "service": "google",
        "credential_type": "agent",
        "supports_delegation": True,
        "delegation_instructions": "Grant Aleq access to your Google Sheets",
    },
    "gsheets.sheet.create": {
        "handler": gsheets_connector.create_sheet,
        "tool_name": "google_sheets.create_sheet",
        "description": "Create new sheet in Google Sheets",
        "requires_oauth": True,
        "service": "google",
        "credential_type": "agent",
        "supports_delegation": True,
        "delegation_instructions": "Grant Aleq access to your Google Sheets",
    },
    "gsheets.batch.update": {
        "handler": gsheets_connector.batch_update,
        "tool_name": "google_sheets.batch_update",
        "description": "Perform batch updates in Google Sheets",
        "requires_oauth": True,
        "service": "google",
        "credential_type": "agent",
        "supports_delegation": True,
        "delegation_instructions": "Grant Aleq access to your Google Sheets",
    },
    "gsheets.range.clear": {
        "handler": gsheets_connector.clear_range,
        "tool_name": "google_sheets.clear_range",
        "description": "Clear values in range in Google Sheets",
        "requires_oauth": True,
        "service": "google",
        "credential_type": "agent",
        "supports_delegation": True,
        "delegation_instructions": "Grant Aleq access to your Google Sheets",
    },
    "gsheets.metadata.get": {
        "handler": gsheets_connector.get_sheet_metadata,
        "tool_name": "google_sheets.get_sheet_metadata",
        "description": "Get metadata about Google Spreadsheet",
        "requires_oauth": True,
        "service": "google",
        "credential_type": "agent",
        "supports_delegation": True,
        "delegation_instructions": "Grant Aleq access to your Google Sheets",
    },
    "gsheets.range.batch_get": {
        "handler": gsheets_connector.batch_get_ranges,
        "tool_name": "google_sheets.batch_get_ranges",
        "description": "Get values from multiple ranges in Google Sheets",
        "requires_oauth": True,
        "service": "google",
        "credential_type": "agent",
        "supports_delegation": True,
        "delegation_instructions": "Grant Aleq access to your Google Sheets",
    },
    "gsheets.spreadsheet.create": {
        "handler": gsheets_connector.create_spreadsheet,
        "tool_name": "google_sheets.create_spreadsheet",
        "description": "Create a new Google Spreadsheet",
        "requires_oauth": True,
        "service": "google",
        "credential_type": "agent",
        "supports_delegation": True,
        "delegation_instructions": "Grant Aleq access to your Google Sheets",
    },
}
