"""
Microsoft 365 Capability Registry
Microsoft Excel, Microsoft OneDrive, Microsoft Outlook Calendar
"""

from app.connectors.microsoft_excel import MicrosoftExcelConnector
from app.connectors.microsoft_onedrive import MicrosoftOneDriveConnector
from app.connectors.microsoft_outlook_calendar import MicrosoftOutlookCalendarConnector

# Initialize connectors
excel_connector = MicrosoftExcelConnector()
onedrive_connector = MicrosoftOneDriveConnector()
outlook_cal_connector = MicrosoftOutlookCalendarConnector()

MICROSOFT_CAPABILITIES = {
    # ========== MICROSOFT EXCEL ==========
    "excel.range.get": {
        "handler": excel_connector.get_range,
        "tool_name": "microsoft_excel.get_range",
        "description": "Get values from range in Excel via Microsoft Graph",
        "requires_oauth": True,
        "service": "microsoft",
        "credential_type": "agent",
        "supports_delegation": True,
        "delegation_instructions": "Grant Aleq access to your Microsoft Excel",
    },
    "excel.range.update": {
        "handler": excel_connector.update_range,
        "tool_name": "microsoft_excel.update_range",
        "description": "Update values in range in Excel via Microsoft Graph",
        "requires_oauth": True,
        "service": "microsoft",
        "credential_type": "agent",
        "supports_delegation": True,
        "delegation_instructions": "Grant Aleq access to your Microsoft Excel",
    },
    "excel.row.append": {
        "handler": excel_connector.append_row,
        "tool_name": "microsoft_excel.append_row",
        "description": "Append row to Excel worksheet via Microsoft Graph",
        "requires_oauth": True,
        "service": "microsoft",
        "credential_type": "agent",
        "supports_delegation": True,
        "delegation_instructions": "Grant Aleq access to your Microsoft Excel",
    },
    "excel.worksheet.create": {
        "handler": excel_connector.create_worksheet,
        "tool_name": "microsoft_excel.create_worksheet",
        "description": "Create new worksheet in Excel via Microsoft Graph",
        "requires_oauth": True,
        "service": "microsoft",
        "credential_type": "agent",
        "supports_delegation": True,
        "delegation_instructions": "Grant Aleq access to your Microsoft Excel",
    },
    "excel.worksheet.list": {
        "handler": excel_connector.get_worksheets,
        "tool_name": "microsoft_excel.get_worksheets",
        "description": "List worksheets in Excel workbook via Microsoft Graph",
        "requires_oauth": True,
        "service": "microsoft",
        "credential_type": "agent",
        "supports_delegation": True,
        "delegation_instructions": "Grant Aleq access to your Microsoft Excel",
    },
    "excel.table.create": {
        "handler": excel_connector.create_table,
        "tool_name": "microsoft_excel.create_table",
        "description": "Create table in Excel worksheet via Microsoft Graph",
        "requires_oauth": True,
        "service": "microsoft",
        "credential_type": "agent",
        "supports_delegation": True,
        "delegation_instructions": "Grant Aleq access to your Microsoft Excel",
    },
    # ========== MICROSOFT ONEDRIVE ==========
    "onedrive.file.upload": {
        "handler": onedrive_connector.upload_file,
        "tool_name": "microsoft_onedrive.upload_file",
        "description": "Upload file to OneDrive via Microsoft Graph",
        "requires_oauth": True,
        "service": "microsoft",
        "credential_type": "agent",
        "supports_delegation": True,
        "delegation_instructions": "Grant Aleq access to your Microsoft OneDrive",
    },
    "onedrive.file.download": {
        "handler": onedrive_connector.download_file,
        "tool_name": "microsoft_onedrive.download_file",
        "description": "Download file from OneDrive via Microsoft Graph",
        "requires_oauth": True,
        "service": "microsoft",
        "credential_type": "agent",
        "supports_delegation": True,
        "delegation_instructions": "Grant Aleq access to your Microsoft OneDrive",
    },
    "onedrive.file.list": {
        "handler": onedrive_connector.list_files,
        "tool_name": "microsoft_onedrive.list_files",
        "description": "List files in OneDrive folder via Microsoft Graph",
        "requires_oauth": True,
        "service": "microsoft",
        "credential_type": "agent",
        "supports_delegation": True,
        "delegation_instructions": "Grant Aleq access to your Microsoft OneDrive",
    },
    "onedrive.folder.create": {
        "handler": onedrive_connector.create_folder,
        "tool_name": "microsoft_onedrive.create_folder",
        "description": "Create folder in OneDrive via Microsoft Graph",
        "requires_oauth": True,
        "service": "microsoft",
        "credential_type": "agent",
        "supports_delegation": True,
        "delegation_instructions": "Grant Aleq access to your Microsoft OneDrive",
    },
    "onedrive.file.metadata": {
        "handler": onedrive_connector.get_file_metadata,
        "tool_name": "microsoft_onedrive.get_file_metadata",
        "description": "Get file metadata from OneDrive via Microsoft Graph",
        "requires_oauth": True,
        "service": "microsoft",
        "credential_type": "agent",
        "supports_delegation": True,
        "delegation_instructions": "Grant Aleq access to your Microsoft OneDrive",
    },
    "onedrive.file.delete": {
        "handler": onedrive_connector.delete_file,
        "tool_name": "microsoft_onedrive.delete_file",
        "description": "Delete a file from OneDrive via Microsoft Graph",
        "requires_oauth": True,
        "service": "microsoft",
        "credential_type": "agent",
        "supports_delegation": True,
        "delegation_instructions": "Grant Aleq access to your Microsoft OneDrive",
    },
    "onedrive.file.search": {
        "handler": onedrive_connector.search_files,
        "tool_name": "microsoft_onedrive.search_files",
        "description": "Search for files in OneDrive via Microsoft Graph",
        "requires_oauth": True,
        "service": "microsoft",
        "credential_type": "agent",
        "supports_delegation": True,
        "delegation_instructions": "Grant Aleq access to your Microsoft OneDrive",
    },
    # ========== MICROSOFT OUTLOOK CALENDAR ==========
    "outlook.event.create": {
        "handler": outlook_cal_connector.create_event,
        "tool_name": "microsoft_outlook_calendar.create_event",
        "description": "Create calendar event in Outlook Calendar via Microsoft Graph",
        "requires_oauth": True,
        "service": "microsoft",
        "credential_type": "agent",
        "supports_delegation": True,
        "delegation_instructions": "Grant Aleq access to your Outlook Calendar",
    },
    "outlook.availability.check": {
        "handler": outlook_cal_connector.check_availability,
        "tool_name": "microsoft_outlook_calendar.check_availability",
        "description": "Check free/busy schedule in Outlook Calendar via Microsoft Graph",
        "requires_oauth": True,
        "service": "microsoft",
        "credential_type": "agent",
        "supports_delegation": True,
        "delegation_instructions": "Grant Aleq access to your Outlook Calendar",
    },
    "outlook.event.update": {
        "handler": outlook_cal_connector.update_event,
        "tool_name": "microsoft_outlook_calendar.update_event",
        "description": "Update calendar event in Outlook Calendar via Microsoft Graph",
        "requires_oauth": True,
        "service": "microsoft",
        "credential_type": "agent",
        "supports_delegation": True,
        "delegation_instructions": "Grant Aleq access to your Outlook Calendar",
    },
    "outlook.event.list": {
        "handler": outlook_cal_connector.list_events,
        "tool_name": "microsoft_outlook_calendar.list_events",
        "description": "List calendar events in Outlook Calendar via Microsoft Graph",
        "requires_oauth": True,
        "service": "microsoft",
        "credential_type": "agent",
        "supports_delegation": True,
        "delegation_instructions": "Grant Aleq access to your Outlook Calendar",
    },
    "outlook.event.cancel": {
        "handler": outlook_cal_connector.cancel_event,
        "tool_name": "microsoft_outlook_calendar.cancel_event",
        "description": "Cancel calendar event in Outlook Calendar via Microsoft Graph",
        "requires_oauth": True,
        "service": "microsoft",
        "credential_type": "agent",
        "supports_delegation": True,
        "delegation_instructions": "Grant Aleq access to your Outlook Calendar",
    },
    "outlook.event.get": {
        "handler": outlook_cal_connector.get_event,
        "tool_name": "microsoft_outlook_calendar.get_event",
        "description": "Get a single calendar event from Outlook Calendar via Microsoft Graph",
        "requires_oauth": True,
        "service": "microsoft",
        "credential_type": "agent",
        "supports_delegation": True,
        "delegation_instructions": "Grant Aleq access to your Outlook Calendar",
    },
    "outlook.calendar.list": {
        "handler": outlook_cal_connector.list_calendars,
        "tool_name": "microsoft_outlook_calendar.list_calendars",
        "description": "List user's calendars in Outlook via Microsoft Graph",
        "requires_oauth": True,
        "service": "microsoft",
        "credential_type": "agent",
        "supports_delegation": True,
        "delegation_instructions": "Grant Aleq access to your Outlook Calendar",
    },
}
