"""
Bill.com Capability Registry.

Registers all Bill.com AP automation capabilities.
"""

from app.connectors.billcom import BillComConnector

# Initialize connector
billcom_connector = BillComConnector()

BILLCOM_CAPABILITIES = {
    # ========== VENDORS ==========
    "billcom.vendor.create": {
        "handler": billcom_connector.create_vendor,
        "tool_name": "billcom.create_vendor",
        "description": "Create a vendor in Bill.com",
        "requires_oauth": False,  # Session-based auth, not OAuth
        "service": "billcom",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "billcom.vendor.get": {
        "handler": billcom_connector.get_vendor,
        "tool_name": "billcom.get_vendor",
        "description": "Get a vendor by ID from Bill.com",
        "requires_oauth": False,
        "service": "billcom",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "billcom.vendor.list": {
        "handler": billcom_connector.list_vendors,
        "tool_name": "billcom.list_vendors",
        "description": "List vendors from Bill.com",
        "requires_oauth": False,
        "service": "billcom",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "billcom.vendor.update": {
        "handler": billcom_connector.update_vendor,
        "tool_name": "billcom.update_vendor",
        "description": "Update a vendor in Bill.com",
        "requires_oauth": False,
        "service": "billcom",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "billcom.vendor.archive": {
        "handler": billcom_connector.archive_vendor,
        "tool_name": "billcom.archive_vendor",
        "description": "Archive a vendor in Bill.com",
        "requires_oauth": False,
        "service": "billcom",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "billcom.vendorcredit.create": {
        "handler": billcom_connector.create_vendor_credit,
        "tool_name": "billcom.create_vendor_credit",
        "description": "Create a vendor credit in Bill.com",
        "requires_oauth": False,
        "service": "billcom",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "billcom.vendorcredit.list": {
        "handler": billcom_connector.list_vendor_credits,
        "tool_name": "billcom.list_vendor_credits",
        "description": "List vendor credits from Bill.com",
        "requires_oauth": False,
        "service": "billcom",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    # ========== BILLS ==========
    "billcom.bill.create": {
        "handler": billcom_connector.create_bill,
        "tool_name": "billcom.create_bill",
        "description": "Create a bill in Bill.com",
        "requires_oauth": False,
        "service": "billcom",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "billcom.bill.get": {
        "handler": billcom_connector.get_bill,
        "tool_name": "billcom.get_bill",
        "description": "Get a bill by ID from Bill.com",
        "requires_oauth": False,
        "service": "billcom",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "billcom.bill.list": {
        "handler": billcom_connector.list_bills,
        "tool_name": "billcom.list_bills",
        "description": "List bills from Bill.com",
        "requires_oauth": False,
        "service": "billcom",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "billcom.bill.update": {
        "handler": billcom_connector.update_bill,
        "tool_name": "billcom.update_bill",
        "description": "Update a bill in Bill.com",
        "requires_oauth": False,
        "service": "billcom",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "billcom.bill.approve": {
        "handler": billcom_connector.approve_bill,
        "tool_name": "billcom.approve_bill",
        "description": "Approve a bill for payment in Bill.com",
        "requires_oauth": False,
        "service": "billcom",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "billcom.bill.archive": {
        "handler": billcom_connector.archive_bill,
        "tool_name": "billcom.archive_bill",
        "description": "Archive a bill in Bill.com",
        "requires_oauth": False,
        "service": "billcom",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "billcom.bill.record_payment": {
        "handler": billcom_connector.record_payment,
        "tool_name": "billcom.record_payment",
        "description": "Record an external payment against bills in Bill.com",
        "requires_oauth": False,
        "service": "billcom",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    # ========== PAYMENTS ==========
    "billcom.payment.create": {
        "handler": billcom_connector.create_payment,
        "tool_name": "billcom.create_payment",
        "description": "Create a payment in Bill.com",
        "requires_oauth": False,
        "service": "billcom",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "billcom.payment.get": {
        "handler": billcom_connector.get_payment,
        "tool_name": "billcom.get_payment",
        "description": "Get a payment by ID from Bill.com",
        "requires_oauth": False,
        "service": "billcom",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "billcom.payment.list": {
        "handler": billcom_connector.list_payments,
        "tool_name": "billcom.list_payments",
        "description": "List payments from Bill.com",
        "requires_oauth": False,
        "service": "billcom",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "billcom.payment.status": {
        "handler": billcom_connector.get_payment_status,
        "tool_name": "billcom.get_payment_status",
        "description": "Get payment status from Bill.com",
        "requires_oauth": False,
        "service": "billcom",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "billcom.payment.cancel": {
        "handler": billcom_connector.cancel_payment,
        "tool_name": "billcom.cancel_payment",
        "description": "Cancel a scheduled payment in Bill.com",
        "requires_oauth": False,
        "service": "billcom",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "billcom.payment.void": {
        "handler": billcom_connector.void_payment,
        "tool_name": "billcom.void_payment",
        "description": "Void a processed payment in Bill.com",
        "requires_oauth": False,
        "service": "billcom",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "billcom.payment.bulk": {
        "handler": billcom_connector.create_bulk_payment,
        "tool_name": "billcom.create_bulk_payment",
        "description": "Create bulk payments in Bill.com",
        "requires_oauth": False,
        "service": "billcom",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    # ========== BANK ACCOUNTS ==========
    "billcom.bankaccount.list": {
        "handler": billcom_connector.list_bank_accounts,
        "tool_name": "billcom.list_bank_accounts",
        "description": "List bank accounts for funding payments in Bill.com",
        "requires_oauth": False,
        "service": "billcom",
        "credential_type": "customer",
        "supports_delegation": False,
    },
}
