"""
Gusto Capability Registry
Payroll, HR, employees, contractors, and tax forms
"""

from app.connectors.gusto import gusto_connector

GUSTO_CAPABILITIES = {
    # ========== COMPANY ==========
    "gusto.company.get": {
        "handler": gusto_connector.get_company,
        "tool_name": "gusto.get_company",
        "description": "Get company details from Gusto",
        "requires_oauth": True,
        "service": "gusto",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "gusto.company.list": {
        "handler": gusto_connector.list_companies,
        "tool_name": "gusto.list_companies",
        "description": "List companies accessible to the user",
        "requires_oauth": True,
        "service": "gusto",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "gusto.locations.list": {
        "handler": gusto_connector.list_locations,
        "tool_name": "gusto.list_locations",
        "description": "List company locations",
        "requires_oauth": True,
        "service": "gusto",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    # ========== EMPLOYEES ==========
    "gusto.employees.list": {
        "handler": gusto_connector.list_employees,
        "tool_name": "gusto.list_employees",
        "description": "List employees for a company",
        "requires_oauth": True,
        "service": "gusto",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "gusto.employee.get": {
        "handler": gusto_connector.get_employee,
        "tool_name": "gusto.get_employee",
        "description": "Get employee details",
        "requires_oauth": True,
        "service": "gusto",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "gusto.employee.create": {
        "handler": gusto_connector.create_employee,
        "tool_name": "gusto.create_employee",
        "description": "Create a new employee",
        "requires_oauth": True,
        "service": "gusto",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "gusto.employee.update": {
        "handler": gusto_connector.update_employee,
        "tool_name": "gusto.update_employee",
        "description": "Update employee information",
        "requires_oauth": True,
        "service": "gusto",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "gusto.employee.terminate": {
        "handler": gusto_connector.terminate_employee,
        "tool_name": "gusto.terminate_employee",
        "description": "Terminate an employee",
        "requires_oauth": True,
        "service": "gusto",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    # ========== PAYROLL ==========
    "gusto.payrolls.list": {
        "handler": gusto_connector.list_payrolls,
        "tool_name": "gusto.list_payrolls",
        "description": "List payrolls for a company",
        "requires_oauth": True,
        "service": "gusto",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "gusto.payroll.get": {
        "handler": gusto_connector.get_payroll,
        "tool_name": "gusto.get_payroll",
        "description": "Get payroll details",
        "requires_oauth": True,
        "service": "gusto",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "gusto.payroll.calculate": {
        "handler": gusto_connector.calculate_payroll,
        "tool_name": "gusto.calculate_payroll",
        "description": "Calculate payroll totals",
        "requires_oauth": True,
        "service": "gusto",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "gusto.payroll.submit": {
        "handler": gusto_connector.submit_payroll,
        "tool_name": "gusto.submit_payroll",
        "description": "Submit payroll for processing",
        "requires_oauth": True,
        "service": "gusto",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    # ========== CONTRACTORS ==========
    "gusto.contractors.list": {
        "handler": gusto_connector.list_contractors,
        "tool_name": "gusto.list_contractors",
        "description": "List contractors for a company",
        "requires_oauth": True,
        "service": "gusto",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "gusto.contractor.get": {
        "handler": gusto_connector.get_contractor,
        "tool_name": "gusto.get_contractor",
        "description": "Get contractor details",
        "requires_oauth": True,
        "service": "gusto",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "gusto.contractor.create": {
        "handler": gusto_connector.create_contractor,
        "tool_name": "gusto.create_contractor",
        "description": "Create a new contractor",
        "requires_oauth": True,
        "service": "gusto",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "gusto.contractor_payments.list": {
        "handler": gusto_connector.list_contractor_payments,
        "tool_name": "gusto.list_contractor_payments",
        "description": "List contractor payments",
        "requires_oauth": True,
        "service": "gusto",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    # ========== TAX FORMS ==========
    "gusto.tax_forms.list": {
        "handler": gusto_connector.list_tax_forms,
        "tool_name": "gusto.list_tax_forms",
        "description": "List tax forms for a company",
        "requires_oauth": True,
        "service": "gusto",
        "credential_type": "customer",
        "supports_delegation": False,
    },
}
