"""
NetSuite Capability Registry
"""

from app.connectors.netsuite import NetSuiteConnector

# Initialize connector
netsuite_connector = NetSuiteConnector()

NETSUITE_CAPABILITIES = {
    # ========== NETSUITE JOURNAL ENTRIES ==========
    "netsuite.journal.create": {
        "handler": netsuite_connector.create_journal_entry,
        "tool_name": "netsuite.create_journal_entry",
        "description": "Create a journal entry in NetSuite (debits must equal credits)",
        "requires_oauth": True,
        "service": "netsuite",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "netsuite.journal.get": {
        "handler": netsuite_connector.get_journal_entry,
        "tool_name": "netsuite.get_journal_entry",
        "description": "Get a journal entry by ID from NetSuite",
        "requires_oauth": True,
        "service": "netsuite",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    # ========== NETSUITE VENDOR BILLS ==========
    "netsuite.vendorbill.create": {
        "handler": netsuite_connector.create_vendor_bill,
        "tool_name": "netsuite.create_vendor_bill",
        "description": "Create a vendor bill in NetSuite",
        "requires_oauth": True,
        "service": "netsuite",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "netsuite.vendorbill.get": {
        "handler": netsuite_connector.get_vendor_bill,
        "tool_name": "netsuite.get_vendor_bill",
        "description": "Get a vendor bill by ID from NetSuite",
        "requires_oauth": True,
        "service": "netsuite",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "netsuite.vendorbill.list": {
        "handler": netsuite_connector.list_vendor_bills,
        "tool_name": "netsuite.list_vendor_bills",
        "description": "List vendor bills with filters (date range, vendor, status)",
        "requires_oauth": True,
        "service": "netsuite",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    # ========== NETSUITE PURCHASE ORDERS ==========
    "netsuite.purchaseorder.create": {
        "handler": netsuite_connector.create_purchase_order,
        "tool_name": "netsuite.create_purchase_order",
        "description": "Create a purchase order in NetSuite",
        "requires_oauth": True,
        "service": "netsuite",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "netsuite.vendor.get": {
        "handler": netsuite_connector.get_vendor,
        "tool_name": "netsuite.get_vendor",
        "description": "Get vendor details from NetSuite",
        "requires_oauth": True,
        "service": "netsuite",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "netsuite.vendor.create": {
        "handler": netsuite_connector.create_vendor,
        "tool_name": "netsuite.create_vendor",
        "description": "Create a vendor in NetSuite",
        "requires_oauth": True,
        "service": "netsuite",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "netsuite.query": {
        "handler": netsuite_connector.query_records,
        "tool_name": "netsuite.query_records",
        "description": "Query records using SuiteQL in NetSuite",
        "requires_oauth": True,
        "service": "netsuite",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "netsuite.subsidiary.list": {
        "handler": netsuite_connector.get_subsidiary_list,
        "tool_name": "netsuite.get_subsidiary_list",
        "description": "Get list of subsidiaries from NetSuite",
        "requires_oauth": True,
        "service": "netsuite",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "netsuite.account.list": {
        "handler": netsuite_connector.get_account_list,
        "tool_name": "netsuite.get_account_list",
        "description": "Get chart of accounts from NetSuite",
        "requires_oauth": True,
        "service": "netsuite",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "netsuite.gl.transactions": {
        "handler": netsuite_connector.get_gl_transactions,
        "tool_name": "netsuite.get_gl_transactions",
        "description": "Get GL transactions for bank reconciliation",
        "requires_oauth": True,
        "service": "netsuite",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "netsuite.reconcile.bank": {
        "handler": netsuite_connector.reconcile_bank_statement,
        "tool_name": "netsuite.reconcile_bank_statement",
        "description": "Reconcile bank statement in NetSuite",
        "requires_oauth": True,
        "service": "netsuite",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "netsuite.customrecord.create": {
        "handler": netsuite_connector.create_custom_record,
        "tool_name": "netsuite.create_custom_record",
        "description": "Create a custom record in NetSuite",
        "requires_oauth": True,
        "service": "netsuite",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "netsuite.vendor.update": {
        "handler": netsuite_connector.update_vendor,
        "tool_name": "netsuite.update_vendor",
        "description": "Update vendor record (address, phone, email, etc.) in NetSuite",
        "requires_oauth": True,
        "service": "netsuite",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "netsuite.vendor.search": {
        "handler": netsuite_connector.query_vendor_by_name,
        "tool_name": "netsuite.query_vendor_by_name",
        "description": "Search for vendors by company name in NetSuite",
        "requires_oauth": True,
        "service": "netsuite",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "netsuite.vendorbill.approve": {
        "handler": netsuite_connector.approve_vendor_bill,
        "tool_name": "netsuite.approve_vendor_bill",
        "description": "Approve a vendor bill in NetSuite",
        "requires_oauth": True,
        "service": "netsuite",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "netsuite.payment.create": {
        "handler": netsuite_connector.create_vendor_payment,
        "tool_name": "netsuite.create_vendor_payment",
        "description": "Create a payment for vendor bills in NetSuite",
        "requires_oauth": True,
        "service": "netsuite",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "netsuite.payment.batch": {
        "handler": netsuite_connector.batch_vendor_payments,
        "tool_name": "netsuite.batch_vendor_payments",
        "description": "Process multiple vendor payments in batch in NetSuite",
        "requires_oauth": True,
        "service": "netsuite",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "netsuite.vendor.upload_document": {
        "handler": netsuite_connector.upload_vendor_document,
        "tool_name": "netsuite.upload_vendor_document",
        "description": "Attach a document (W-9, contract, etc.) to vendor record in NetSuite",
        "requires_oauth": True,
        "service": "netsuite",
        "credential_type": "customer",
        "supports_delegation": False,
    },
}
