"""
QuickBooks Core Capability Registry - Vendors, Bills, Journals, Customers
"""

from app.connectors.quickbooks import QuickBooksConnector

# Initialize connector
qb_connector = QuickBooksConnector()

QUICKBOOKS_CORE_CAPABILITIES = {
    # ========== VENDOR OPERATIONS ==========
    "vendor.create": {
        "handler": qb_connector.create_vendor,
        "tool_name": "quickbooks.create_vendor",
        "description": "Create a vendor in QuickBooks",
        "requires_oauth": True,
        "service": "quickbooks",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "vendor.get": {
        "handler": qb_connector.get_vendor,
        "tool_name": "quickbooks.get_vendor",
        "description": "Get vendor details from QuickBooks",
        "requires_oauth": True,
        "service": "quickbooks",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "vendor.list": {
        "handler": qb_connector.list_vendors,
        "tool_name": "quickbooks.list_vendors",
        "description": "List vendors from QuickBooks",
        "requires_oauth": True,
        "service": "quickbooks",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "vendor.search": {
        "handler": qb_connector.search_vendors,
        "tool_name": "quickbooks.search_vendors",
        "description": "Search vendors by name with fuzzy matching",
        "requires_oauth": True,
        "service": "quickbooks",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "vendor.update": {
        "handler": qb_connector.update_vendor,
        "tool_name": "quickbooks.update_vendor",
        "description": "Update vendor details",
        "requires_oauth": True,
        "service": "quickbooks",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    # ========== BILL OPERATIONS ==========
    "bill.create": {
        "handler": qb_connector.create_bill,
        "tool_name": "quickbooks.create_bill",
        "description": "Create a bill in QuickBooks",
        "requires_oauth": True,
        "service": "quickbooks",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "bill.list": {
        "handler": qb_connector.list_bills,
        "tool_name": "quickbooks.list_bills",
        "description": "List bills with optional vendor/date filters",
        "requires_oauth": True,
        "service": "quickbooks",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "bill.get": {
        "handler": qb_connector.get_bill,
        "tool_name": "quickbooks.get_bill",
        "description": "Get bill details including line items",
        "requires_oauth": True,
        "service": "quickbooks",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "bill.update": {
        "handler": qb_connector.update_bill,
        "tool_name": "quickbooks.update_bill",
        "description": "Update a bill in QuickBooks",
        "requires_oauth": True,
        "service": "quickbooks",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "bill.payment.create": {
        "handler": qb_connector.create_bill_payment,
        "tool_name": "quickbooks.create_bill_payment",
        "description": "Create a bill payment in QuickBooks",
        "requires_oauth": True,
        "service": "quickbooks",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "billpayment.list": {
        "handler": qb_connector.list_bill_payments,
        "tool_name": "quickbooks.list_bill_payments",
        "description": "List vendor bill payments with optional filters",
        "requires_oauth": True,
        "service": "quickbooks",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    # ========== JOURNAL & QUERY ==========
    "journal.create": {
        "handler": qb_connector.create_journal_entry,
        "tool_name": "quickbooks.create_journal_entry",
        "description": "Create a journal entry in QuickBooks",
        "requires_oauth": True,
        "service": "quickbooks",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "journal.get": {
        "handler": qb_connector.get_journal_entry,
        "tool_name": "quickbooks.get_journal_entry",
        "description": "Get a journal entry from QuickBooks",
        "requires_oauth": True,
        "service": "quickbooks",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "journal.list": {
        "handler": qb_connector.list_journal_entries,
        "tool_name": "quickbooks.list_journal_entries",
        "description": "List journal entries from QuickBooks",
        "requires_oauth": True,
        "service": "quickbooks",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "qb.query": {
        "handler": qb_connector.query_entities,
        "tool_name": "quickbooks.query_entities",
        "description": "Query QuickBooks entities using SQL-like syntax",
        "requires_oauth": True,
        "service": "quickbooks",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    # ========== EXPENSE & PURCHASE ORDER ==========
    "purchaseorder.create": {
        "handler": qb_connector.create_purchase_order,
        "tool_name": "quickbooks.create_purchase_order",
        "description": "Create a purchase order in QuickBooks",
        "requires_oauth": True,
        "service": "quickbooks",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "purchaseorder.get": {
        "handler": qb_connector.get_purchase_order,
        "tool_name": "quickbooks.get_purchase_order",
        "description": "Get purchase order details including line items",
        "requires_oauth": True,
        "service": "quickbooks",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "purchaseorder.list": {
        "handler": qb_connector.list_purchase_orders,
        "tool_name": "quickbooks.list_purchase_orders",
        "description": "List purchase orders with optional vendor/status filters",
        "requires_oauth": True,
        "service": "quickbooks",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "expense.create": {
        "handler": qb_connector.create_expense,
        "tool_name": "quickbooks.create_expense",
        "description": "Create an expense in QuickBooks",
        "requires_oauth": True,
        "service": "quickbooks",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    # ========== CHART OF ACCOUNTS ==========
    "chartofaccounts.get": {
        "handler": qb_connector.get_chart_of_accounts,
        "tool_name": "quickbooks.get_chart_of_accounts",
        "description": "Get chart of accounts from QuickBooks",
        "requires_oauth": True,
        "service": "quickbooks",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "account.list": {
        "handler": qb_connector.get_chart_of_accounts,
        "tool_name": "quickbooks.get_chart_of_accounts",
        "description": "List all accounts (chart of accounts)",
        "requires_oauth": True,
        "service": "quickbooks",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "account.get": {
        "handler": qb_connector.get_account,
        "tool_name": "quickbooks.get_account",
        "description": "Get single account details with balance",
        "requires_oauth": True,
        "service": "quickbooks",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    # ========== CUSTOMER OPERATIONS ==========
    "qb.customer.create": {
        "handler": qb_connector.create_customer,
        "tool_name": "quickbooks.create_customer",
        "description": "Create a customer in QuickBooks",
        "requires_oauth": True,
        "service": "quickbooks",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "qb.customer.get": {
        "handler": qb_connector.get_customer,
        "tool_name": "quickbooks.get_customer",
        "description": "Get customer details from QuickBooks",
        "requires_oauth": True,
        "service": "quickbooks",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "qb.customer.update": {
        "handler": qb_connector.update_customer,
        "tool_name": "quickbooks.update_customer",
        "description": "Update a customer in QuickBooks",
        "requires_oauth": True,
        "service": "quickbooks",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "qb.customer.list": {
        "handler": qb_connector.list_customers,
        "tool_name": "quickbooks.list_customers",
        "description": "List customers from QuickBooks",
        "requires_oauth": True,
        "service": "quickbooks",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "qb.customer.search": {
        "handler": qb_connector.search_customers,
        "tool_name": "quickbooks.search_customers",
        "description": "Search customers by name with fuzzy matching",
        "requires_oauth": True,
        "service": "quickbooks",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    # ========== MARS CUSTOMER COMPATIBILITY ALIASES ==========
    "customer.create": {
        "handler": qb_connector.create_customer,
        "tool_name": "quickbooks.create_customer",
        "description": "Create a customer in QuickBooks (MARS compatibility alias)",
        "requires_oauth": True,
        "service": "quickbooks",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "customer.get": {
        "handler": qb_connector.get_customer,
        "tool_name": "quickbooks.get_customer",
        "description": "Get customer details from QuickBooks (MARS compatibility alias)",
        "requires_oauth": True,
        "service": "quickbooks",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "customer.update": {
        "handler": qb_connector.update_customer,
        "tool_name": "quickbooks.update_customer",
        "description": "Update a customer in QuickBooks (MARS compatibility alias)",
        "requires_oauth": True,
        "service": "quickbooks",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "customer.list": {
        "handler": qb_connector.list_customers,
        "tool_name": "quickbooks.list_customers",
        "description": "List customers from QuickBooks (MARS compatibility alias)",
        "requires_oauth": True,
        "service": "quickbooks",
        "credential_type": "customer",
        "supports_delegation": False,
    },
}
