"""
QuickBooks Invoice & Sales Capability Registry
"""

from app.connectors.quickbooks import QuickBooksConnector

# Initialize connector
qb_connector = QuickBooksConnector()

QUICKBOOKS_INVOICE_CAPABILITIES = {
    # ========== INVOICE OPERATIONS ==========
    "qb.invoice.create": {
        "handler": qb_connector.create_invoice,
        "tool_name": "quickbooks.create_invoice",
        "description": "Create an invoice in QuickBooks",
        "requires_oauth": True,
        "service": "quickbooks",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "qb.invoice.get": {
        "handler": qb_connector.get_invoice,
        "tool_name": "quickbooks.get_invoice",
        "description": "Get invoice details from QuickBooks",
        "requires_oauth": True,
        "service": "quickbooks",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "qb.invoice.send": {
        "handler": qb_connector.send_invoice,
        "tool_name": "quickbooks.send_invoice",
        "description": "Send invoice via email through QuickBooks",
        "requires_oauth": True,
        "service": "quickbooks",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "qb.invoice.void": {
        "handler": qb_connector.void_invoice,
        "tool_name": "quickbooks.void_invoice",
        "description": "Void an invoice in QuickBooks",
        "requires_oauth": True,
        "service": "quickbooks",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "qb.invoice.list": {
        "handler": qb_connector.list_invoices,
        "tool_name": "quickbooks.list_invoices",
        "description": "List invoices from QuickBooks",
        "requires_oauth": True,
        "service": "quickbooks",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "qb.invoice.list_outstanding": {
        "handler": qb_connector.list_outstanding_invoices,
        "tool_name": "quickbooks.list_outstanding_invoices",
        "description": (
            "List outstanding invoices (Balance > 0) from QuickBooks - "
            "CRITICAL for MARS payment allocation"
        ),
        "requires_oauth": True,
        "service": "quickbooks",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    # ========== MARS INVOICE COMPATIBILITY ALIASES ==========
    "invoice.create": {
        "handler": qb_connector.create_invoice,
        "tool_name": "quickbooks.create_invoice",
        "description": "Create an invoice in QuickBooks (MARS compatibility alias)",
        "requires_oauth": True,
        "service": "quickbooks",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "invoice.get": {
        "handler": qb_connector.get_invoice,
        "tool_name": "quickbooks.get_invoice",
        "description": "Get invoice details from QuickBooks (MARS compatibility alias)",
        "requires_oauth": True,
        "service": "quickbooks",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "invoice.send": {
        "handler": qb_connector.send_invoice,
        "tool_name": "quickbooks.send_invoice",
        "description": "Send invoice via email through QuickBooks (MARS compatibility alias)",
        "requires_oauth": True,
        "service": "quickbooks",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "invoice.void": {
        "handler": qb_connector.void_invoice,
        "tool_name": "quickbooks.void_invoice",
        "description": "Void an invoice in QuickBooks (MARS compatibility alias)",
        "requires_oauth": True,
        "service": "quickbooks",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "invoice.list": {
        "handler": qb_connector.list_invoices,
        "tool_name": "quickbooks.list_invoices",
        "description": "List invoices from QuickBooks (MARS compatibility alias)",
        "requires_oauth": True,
        "service": "quickbooks",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    # ========== ITEM OPERATIONS ==========
    "item.create": {
        "handler": qb_connector.create_item,
        "tool_name": "quickbooks.create_item",
        "description": "Create an item/product in QuickBooks",
        "requires_oauth": True,
        "service": "quickbooks",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "item.get": {
        "handler": qb_connector.get_item,
        "tool_name": "quickbooks.get_item",
        "description": "Get item details from QuickBooks",
        "requires_oauth": True,
        "service": "quickbooks",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "item.list": {
        "handler": qb_connector.list_items,
        "tool_name": "quickbooks.list_items",
        "description": "List items from QuickBooks",
        "requires_oauth": True,
        "service": "quickbooks",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    # ========== PAYMENT OPERATIONS ==========
    "qb.payment.create": {
        "handler": qb_connector.create_payment,
        "tool_name": "quickbooks.create_payment",
        "description": "Create a payment (customer payment) in QuickBooks",
        "requires_oauth": True,
        "service": "quickbooks",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "qb.payment.get": {
        "handler": qb_connector.get_payment,
        "tool_name": "quickbooks.get_payment",
        "description": "Get payment details from QuickBooks",
        "requires_oauth": True,
        "service": "quickbooks",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "payment.apply_to_invoice": {
        "handler": qb_connector.apply_payment_to_invoice,
        "tool_name": "quickbooks.apply_payment_to_invoice",
        "description": (
            "Apply payment to specific invoice(s) with Line item references - "
            "enables multi-invoice payment allocation"
        ),
        "requires_oauth": True,
        "service": "quickbooks",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "payment.list": {
        "handler": qb_connector.list_payments,
        "tool_name": "quickbooks.list_payments",
        "description": "List customer payments with optional filters",
        "requires_oauth": True,
        "service": "quickbooks",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    # ========== ESTIMATE, SALES, CREDIT ==========
    "estimate.create": {
        "handler": qb_connector.create_estimate,
        "tool_name": "quickbooks.create_estimate",
        "description": "Create an estimate in QuickBooks",
        "requires_oauth": True,
        "service": "quickbooks",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "estimate.get": {
        "handler": qb_connector.get_estimate,
        "tool_name": "quickbooks.get_estimate",
        "description": "Get estimate details from QuickBooks",
        "requires_oauth": True,
        "service": "quickbooks",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "salesreceipt.create": {
        "handler": qb_connector.create_sales_receipt,
        "tool_name": "quickbooks.create_sales_receipt",
        "description": "Create a sales receipt in QuickBooks",
        "requires_oauth": True,
        "service": "quickbooks",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "creditmemo.create": {
        "handler": qb_connector.create_credit_memo,
        "tool_name": "quickbooks.create_credit_memo",
        "description": "Create a credit memo in QuickBooks",
        "requires_oauth": True,
        "service": "quickbooks",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "timeactivity.create": {
        "handler": qb_connector.create_time_activity,
        "tool_name": "quickbooks.create_time_activity",
        "description": "Create a time activity in QuickBooks",
        "requires_oauth": True,
        "service": "quickbooks",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "refundreceipt.create": {
        "handler": qb_connector.create_refund_receipt,
        "tool_name": "quickbooks.create_refund_receipt",
        "description": "Create a refund receipt",
        "requires_oauth": True,
        "service": "quickbooks",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    # ========== DEPOSIT & TRANSFER ==========
    "deposit.create": {
        "handler": qb_connector.create_deposit,
        "tool_name": "quickbooks.create_deposit",
        "description": "Create a bank deposit",
        "requires_oauth": True,
        "service": "quickbooks",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "qb.transfer.create": {
        "handler": qb_connector.create_transfer,
        "tool_name": "quickbooks.create_transfer",
        "description": "Create account-to-account transfer",
        "requires_oauth": True,
        "service": "quickbooks",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "transaction.list": {
        "handler": qb_connector.list_transactions,
        "tool_name": "quickbooks.list_transactions",
        "description": "List GL transactions for reconciliation",
        "requires_oauth": True,
        "service": "quickbooks",
        "credential_type": "customer",
        "supports_delegation": False,
    },
}
