"""
Square Capability Registry
Payments, orders, customers, invoices, locations, payouts
"""

from app.connectors.square import square_connector

SQUARE_CAPABILITIES = {
    # ========== LOCATIONS ==========
    "square.locations.list": {
        "handler": square_connector.list_locations,
        "tool_name": "square.list_locations",
        "description": "List Square locations",
        "requires_oauth": True,
        "service": "square",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "square.location.get": {
        "handler": square_connector.get_location,
        "tool_name": "square.get_location",
        "description": "Get location details",
        "requires_oauth": True,
        "service": "square",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    # ========== PAYMENTS ==========
    "square.payments.list": {
        "handler": square_connector.list_payments,
        "tool_name": "square.list_payments",
        "description": "List Square payments",
        "requires_oauth": True,
        "service": "square",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "square.payment.get": {
        "handler": square_connector.get_payment,
        "tool_name": "square.get_payment",
        "description": "Get payment details",
        "requires_oauth": True,
        "service": "square",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "square.payment.create": {
        "handler": square_connector.create_payment,
        "tool_name": "square.create_payment",
        "description": "Create a payment",
        "requires_oauth": True,
        "service": "square",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "square.payment.refund": {
        "handler": square_connector.refund_payment,
        "tool_name": "square.refund_payment",
        "description": "Refund a payment",
        "requires_oauth": True,
        "service": "square",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    # ========== ORDERS ==========
    "square.orders.search": {
        "handler": square_connector.search_orders,
        "tool_name": "square.search_orders",
        "description": "Search Square orders",
        "requires_oauth": True,
        "service": "square",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "square.order.get": {
        "handler": square_connector.get_order,
        "tool_name": "square.get_order",
        "description": "Get order details",
        "requires_oauth": True,
        "service": "square",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "square.order.create": {
        "handler": square_connector.create_order,
        "tool_name": "square.create_order",
        "description": "Create an order",
        "requires_oauth": True,
        "service": "square",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "square.order.update": {
        "handler": square_connector.update_order,
        "tool_name": "square.update_order",
        "description": "Update an order",
        "requires_oauth": True,
        "service": "square",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "square.order.pay": {
        "handler": square_connector.pay_order,
        "tool_name": "square.pay_order",
        "description": "Pay for an order",
        "requires_oauth": True,
        "service": "square",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    # ========== CUSTOMERS ==========
    "square.customers.list": {
        "handler": square_connector.list_customers,
        "tool_name": "square.list_customers",
        "description": "List Square customers",
        "requires_oauth": True,
        "service": "square",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "square.customer.get": {
        "handler": square_connector.get_customer,
        "tool_name": "square.get_customer",
        "description": "Get customer details",
        "requires_oauth": True,
        "service": "square",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "square.customer.create": {
        "handler": square_connector.create_customer,
        "tool_name": "square.create_customer",
        "description": "Create a customer",
        "requires_oauth": True,
        "service": "square",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    # ========== INVOICES ==========
    "square.invoices.list": {
        "handler": square_connector.list_invoices,
        "tool_name": "square.list_invoices",
        "description": "List Square invoices",
        "requires_oauth": True,
        "service": "square",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "square.invoice.get": {
        "handler": square_connector.get_invoice,
        "tool_name": "square.get_invoice",
        "description": "Get invoice details",
        "requires_oauth": True,
        "service": "square",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "square.invoice.create": {
        "handler": square_connector.create_invoice,
        "tool_name": "square.create_invoice",
        "description": "Create an invoice",
        "requires_oauth": True,
        "service": "square",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "square.invoice.publish": {
        "handler": square_connector.publish_invoice,
        "tool_name": "square.publish_invoice",
        "description": "Publish an invoice",
        "requires_oauth": True,
        "service": "square",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    # ========== PAYOUTS ==========
    "square.payouts.list": {
        "handler": square_connector.list_payouts,
        "tool_name": "square.list_payouts",
        "description": "List Square payouts",
        "requires_oauth": True,
        "service": "square",
        "credential_type": "customer",
        "supports_delegation": False,
    },
}
