"""
Stripe Billing Capability Registry - Payment Methods, Refunds, Subscriptions, Balance
"""

from app.connectors.stripe import StripeConnector

# Initialize connector
stripe_connector = StripeConnector()

STRIPE_BILLING_CAPABILITIES = {
    # ========== PAYMENT METHODS ==========
    "paymentmethod.create": {
        "handler": stripe_connector.create_payment_method,
        "tool_name": "stripe.create_payment_method",
        "description": "Create a payment method in Stripe",
        "requires_oauth": True,
        "service": "stripe",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "paymentmethod.retrieve": {
        "handler": stripe_connector.retrieve_payment_method,
        "tool_name": "stripe.retrieve_payment_method",
        "description": "Retrieve a payment method in Stripe",
        "requires_oauth": True,
        "service": "stripe",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "paymentmethod.update": {
        "handler": stripe_connector.update_payment_method,
        "tool_name": "stripe.update_payment_method",
        "description": "Update a payment method in Stripe",
        "requires_oauth": True,
        "service": "stripe",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "paymentmethod.list": {
        "handler": stripe_connector.list_payment_methods,
        "tool_name": "stripe.list_payment_methods",
        "description": "List payment methods for a customer",
        "requires_oauth": True,
        "service": "stripe",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "paymentmethod.attach": {
        "handler": stripe_connector.attach_payment_method,
        "tool_name": "stripe.attach_payment_method",
        "description": "Attach a payment method to a customer",
        "requires_oauth": True,
        "service": "stripe",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "paymentmethod.detach": {
        "handler": stripe_connector.detach_payment_method,
        "tool_name": "stripe.detach_payment_method",
        "description": "Detach a payment method from a customer",
        "requires_oauth": True,
        "service": "stripe",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    # ========== REFUNDS ==========
    "refund.retrieve": {
        "handler": stripe_connector.retrieve_refund,
        "tool_name": "stripe.retrieve_refund",
        "description": "Retrieve a refund in Stripe",
        "requires_oauth": True,
        "service": "stripe",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "refund.update": {
        "handler": stripe_connector.update_refund,
        "tool_name": "stripe.update_refund",
        "description": "Update a refund in Stripe",
        "requires_oauth": True,
        "service": "stripe",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "refund.cancel": {
        "handler": stripe_connector.cancel_refund,
        "tool_name": "stripe.cancel_refund",
        "description": "Cancel a refund in Stripe",
        "requires_oauth": True,
        "service": "stripe",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "refund.list": {
        "handler": stripe_connector.list_refunds,
        "tool_name": "stripe.list_refunds",
        "description": "List refunds in Stripe",
        "requires_oauth": True,
        "service": "stripe",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    # ========== DISPUTES ==========
    "dispute.retrieve": {
        "handler": stripe_connector.retrieve_dispute,
        "tool_name": "stripe.retrieve_dispute",
        "description": "Retrieve a dispute in Stripe",
        "requires_oauth": True,
        "service": "stripe",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "dispute.update": {
        "handler": stripe_connector.update_dispute,
        "tool_name": "stripe.update_dispute",
        "description": "Update a dispute with evidence in Stripe",
        "requires_oauth": True,
        "service": "stripe",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "dispute.close": {
        "handler": stripe_connector.close_dispute,
        "tool_name": "stripe.close_dispute",
        "description": "Close a dispute in Stripe",
        "requires_oauth": True,
        "service": "stripe",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "dispute.list": {
        "handler": stripe_connector.list_disputes,
        "tool_name": "stripe.list_disputes",
        "description": "List disputes in Stripe",
        "requires_oauth": True,
        "service": "stripe",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    # ========== CHARGES ==========
    "charge.retrieve": {
        "handler": stripe_connector.retrieve_charge,
        "tool_name": "stripe.retrieve_charge",
        "description": "Retrieve a charge in Stripe",
        "requires_oauth": True,
        "service": "stripe",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "charge.list": {
        "handler": stripe_connector.list_charges,
        "tool_name": "stripe.list_charges",
        "description": "List charges in Stripe",
        "requires_oauth": True,
        "service": "stripe",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    # ========== SUBSCRIPTIONS ==========
    "subscription.create": {
        "handler": stripe_connector.create_subscription,
        "tool_name": "stripe.create_subscription",
        "description": "Create a subscription in Stripe",
        "requires_oauth": True,
        "service": "stripe",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "subscription.retrieve": {
        "handler": stripe_connector.retrieve_subscription,
        "tool_name": "stripe.retrieve_subscription",
        "description": "Retrieve a subscription in Stripe",
        "requires_oauth": True,
        "service": "stripe",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "subscription.update": {
        "handler": stripe_connector.update_subscription,
        "tool_name": "stripe.update_subscription",
        "description": "Update a subscription in Stripe",
        "requires_oauth": True,
        "service": "stripe",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "subscription.cancel": {
        "handler": stripe_connector.cancel_subscription,
        "tool_name": "stripe.cancel_subscription",
        "description": "Cancel a subscription in Stripe",
        "requires_oauth": True,
        "service": "stripe",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "subscription.list": {
        "handler": stripe_connector.list_subscriptions,
        "tool_name": "stripe.list_subscriptions",
        "description": "List subscriptions in Stripe",
        "requires_oauth": True,
        "service": "stripe",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    # ========== BALANCE & PAYOUTS ==========
    "balance.get": {
        "handler": stripe_connector.get_balance,
        "tool_name": "stripe.get_balance",
        "description": "Get current Stripe balance",
        "requires_oauth": True,
        "service": "stripe",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "payout.list": {
        "handler": stripe_connector.list_payouts,
        "tool_name": "stripe.list_payouts",
        "description": "List Stripe payouts",
        "requires_oauth": True,
        "service": "stripe",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "payout.retrieve": {
        "handler": stripe_connector.retrieve_payout,
        "tool_name": "stripe.retrieve_payout",
        "description": "Retrieve a specific Stripe payout",
        "requires_oauth": True,
        "service": "stripe",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "balance.transactions.list": {
        "handler": stripe_connector.list_balance_transactions,
        "tool_name": "stripe.list_balance_transactions",
        "description": "List Stripe balance transactions",
        "requires_oauth": True,
        "service": "stripe",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    # ========== TRANSFERS (Connect) ==========
    "stripe.transfer.create": {
        "handler": stripe_connector.create_transfer,
        "tool_name": "stripe.create_transfer",
        "description": "Create a transfer to connected account (Connect)",
        "requires_oauth": True,
        "service": "stripe",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "stripe.transfer.list": {
        "handler": stripe_connector.list_transfers,
        "tool_name": "stripe.list_transfers",
        "description": "List transfers to connected accounts",
        "requires_oauth": True,
        "service": "stripe",
        "credential_type": "customer",
        "supports_delegation": False,
    },
}
