"""
Stripe Core Capability Registry - Payments, Customers, Products, Checkout, Invoices
"""

from app.connectors.stripe import StripeConnector

# Initialize connector
stripe_connector = StripeConnector()

STRIPE_CORE_CAPABILITIES = {
    # ========== PAYMENT INTENTS ==========
    "payment.create": {
        "handler": stripe_connector.create_payment_intent,
        "tool_name": "stripe.create_payment_intent",
        "description": "Create a payment intent in Stripe",
        "requires_oauth": False,
        "service": "stripe",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "payment.refund": {
        "handler": stripe_connector.refund_payment,
        "tool_name": "stripe.refund_payment",
        "description": "Refund a payment in Stripe",
        "requires_oauth": False,
        "service": "stripe",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "payment.retrieve": {
        "handler": stripe_connector.retrieve_payment_intent,
        "tool_name": "stripe.retrieve_payment_intent",
        "description": "Retrieve a payment intent in Stripe",
        "requires_oauth": False,
        "service": "stripe",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    # ========== CUSTOMERS ==========
    "stripe.customer.create": {
        "handler": stripe_connector.create_customer,
        "tool_name": "stripe.create_customer",
        "description": "Create a customer in Stripe",
        "requires_oauth": False,
        "service": "stripe",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "stripe.customer.retrieve": {
        "handler": stripe_connector.retrieve_customer,
        "tool_name": "stripe.retrieve_customer",
        "description": "Retrieve a customer in Stripe",
        "requires_oauth": False,
        "service": "stripe",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "stripe.customer.update": {
        "handler": stripe_connector.update_customer,
        "tool_name": "stripe.update_customer",
        "description": "Update a customer in Stripe",
        "requires_oauth": False,
        "service": "stripe",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "stripe.customer.list": {
        "handler": stripe_connector.list_customers,
        "tool_name": "stripe.list_customers",
        "description": "List customers in Stripe",
        "requires_oauth": False,
        "service": "stripe",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "stripe.customer.delete": {
        "handler": stripe_connector.delete_customer,
        "tool_name": "stripe.delete_customer",
        "description": "Delete a customer in Stripe",
        "requires_oauth": False,
        "service": "stripe",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "stripe.customer.search": {
        "handler": stripe_connector.search_customers,
        "tool_name": "stripe.search_customers",
        "description": "Search customers in Stripe",
        "requires_oauth": False,
        "service": "stripe",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    # ========== PRODUCTS ==========
    "product.create": {
        "handler": stripe_connector.create_product,
        "tool_name": "stripe.create_product",
        "description": "Create a product in Stripe",
        "requires_oauth": False,
        "service": "stripe",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "product.retrieve": {
        "handler": stripe_connector.retrieve_product,
        "tool_name": "stripe.retrieve_product",
        "description": "Retrieve a product in Stripe",
        "requires_oauth": False,
        "service": "stripe",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "product.update": {
        "handler": stripe_connector.update_product,
        "tool_name": "stripe.update_product",
        "description": "Update a product in Stripe",
        "requires_oauth": False,
        "service": "stripe",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "product.list": {
        "handler": stripe_connector.list_products,
        "tool_name": "stripe.list_products",
        "description": "List products in Stripe",
        "requires_oauth": False,
        "service": "stripe",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "product.delete": {
        "handler": stripe_connector.delete_product,
        "tool_name": "stripe.delete_product",
        "description": "Delete a product in Stripe",
        "requires_oauth": False,
        "service": "stripe",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "product.search": {
        "handler": stripe_connector.search_products,
        "tool_name": "stripe.search_products",
        "description": "Search products in Stripe",
        "requires_oauth": False,
        "service": "stripe",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    # ========== PRICES ==========
    "price.create": {
        "handler": stripe_connector.create_price,
        "tool_name": "stripe.create_price",
        "description": "Create a price in Stripe",
        "requires_oauth": False,
        "service": "stripe",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "price.retrieve": {
        "handler": stripe_connector.retrieve_price,
        "tool_name": "stripe.retrieve_price",
        "description": "Retrieve a price in Stripe",
        "requires_oauth": False,
        "service": "stripe",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "price.update": {
        "handler": stripe_connector.update_price,
        "tool_name": "stripe.update_price",
        "description": "Update a price in Stripe",
        "requires_oauth": False,
        "service": "stripe",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "price.list": {
        "handler": stripe_connector.list_prices,
        "tool_name": "stripe.list_prices",
        "description": "List prices in Stripe",
        "requires_oauth": False,
        "service": "stripe",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "price.search": {
        "handler": stripe_connector.search_prices,
        "tool_name": "stripe.search_prices",
        "description": "Search prices in Stripe",
        "requires_oauth": False,
        "service": "stripe",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    # ========== CHECKOUT SESSIONS ==========
    "checkout.session.create": {
        "handler": stripe_connector.create_checkout_session,
        "tool_name": "stripe.create_checkout_session",
        "description": "Create a Checkout Session in Stripe",
        "requires_oauth": False,
        "service": "stripe",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "checkout.session.retrieve": {
        "handler": stripe_connector.retrieve_checkout_session,
        "tool_name": "stripe.retrieve_checkout_session",
        "description": "Retrieve a Checkout Session in Stripe",
        "requires_oauth": False,
        "service": "stripe",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "checkout.session.expire": {
        "handler": stripe_connector.expire_checkout_session,
        "tool_name": "stripe.expire_checkout_session",
        "description": "Expire a Checkout Session in Stripe",
        "requires_oauth": False,
        "service": "stripe",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "checkout.session.list": {
        "handler": stripe_connector.list_checkout_sessions,
        "tool_name": "stripe.list_checkout_sessions",
        "description": "List Checkout Sessions in Stripe",
        "requires_oauth": False,
        "service": "stripe",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "checkout.lineitems.list": {
        "handler": stripe_connector.list_checkout_line_items,
        "tool_name": "stripe.list_checkout_line_items",
        "description": "List line items for a Checkout Session",
        "requires_oauth": False,
        "service": "stripe",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    # ========== INVOICES ==========
    "stripe.invoice.create": {
        "handler": stripe_connector.create_invoice,
        "tool_name": "stripe.create_invoice",
        "description": "Create an invoice in Stripe",
        "requires_oauth": False,
        "service": "stripe",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "stripe.invoice.retrieve": {
        "handler": stripe_connector.retrieve_invoice,
        "tool_name": "stripe.retrieve_invoice",
        "description": "Retrieve an invoice in Stripe",
        "requires_oauth": False,
        "service": "stripe",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "stripe.invoice.update": {
        "handler": stripe_connector.update_invoice,
        "tool_name": "stripe.update_invoice",
        "description": "Update an invoice in Stripe",
        "requires_oauth": False,
        "service": "stripe",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "stripe.invoice.finalize": {
        "handler": stripe_connector.finalize_invoice,
        "tool_name": "stripe.finalize_invoice",
        "description": "Finalize an invoice in Stripe",
        "requires_oauth": False,
        "service": "stripe",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "stripe.invoice.pay": {
        "handler": stripe_connector.pay_invoice,
        "tool_name": "stripe.pay_invoice",
        "description": "Pay an invoice in Stripe",
        "requires_oauth": False,
        "service": "stripe",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "stripe.invoice.send": {
        "handler": stripe_connector.send_invoice,
        "tool_name": "stripe.send_invoice",
        "description": "Send an invoice in Stripe",
        "requires_oauth": False,
        "service": "stripe",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "stripe.invoice.void": {
        "handler": stripe_connector.void_invoice,
        "tool_name": "stripe.void_invoice",
        "description": "Void an invoice in Stripe",
        "requires_oauth": False,
        "service": "stripe",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "stripe.invoice.list": {
        "handler": stripe_connector.list_invoices,
        "tool_name": "stripe.list_invoices",
        "description": "List invoices in Stripe",
        "requires_oauth": False,
        "service": "stripe",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "stripe.invoice.delete": {
        "handler": stripe_connector.delete_invoice,
        "tool_name": "stripe.delete_invoice",
        "description": "Delete a draft invoice in Stripe",
        "requires_oauth": False,
        "service": "stripe",
        "credential_type": "customer",
        "supports_delegation": False,
    },
}
