"""
Stripe Radar Capability Schemas.

Rich metadata for fraud prevention and risk management.
"""

from app.errors import ErrorCode
from app.schemas.base import (
    CapabilitySchema,
    ErrorHint,
    ParameterSchema,
    ReturnFieldSchema,
)

# ============ EARLY FRAUD WARNINGS ============

EARLY_FRAUD_WARNING_RETRIEVE = CapabilitySchema(
    capability_key="stripe.radar.early_fraud_warning.retrieve",
    service="stripe",
    category="radar",
    description="Retrieve an early fraud warning",
    description_detailed=(
        "Retrieves an early fraud warning indicating a charge is potentially "
        "fraudulent. Issued when card networks report suspected fraud."
    ),
    parameters={
        "warning_id": ParameterSchema(
            type="string",
            required=True,
            description="Early fraud warning ID",
            example="issfr_ABC123",
        ),
    },
    returns={
        "id": ReturnFieldSchema(type="string", description="Warning ID"),
        "charge": ReturnFieldSchema(type="string", description="Charge ID"),
        "payment_intent": ReturnFieldSchema(type="string", description="PI ID"),
        "fraud_type": ReturnFieldSchema(type="string", description="Type of fraud"),
        "actionable": ReturnFieldSchema(type="boolean", description="Is actionable"),
        "created": ReturnFieldSchema(type="integer", description="Unix timestamp"),
    },
    errors=[
        ErrorHint(
            error_code=ErrorCode.CREDENTIALS_MISSING,
            description="Stripe API key not configured",
            recovery_hint="Set STRIPE_SECRET_KEY environment variable",
        ),
    ],
    idempotent=True,
    has_side_effects=False,
)

EARLY_FRAUD_WARNING_LIST = CapabilitySchema(
    capability_key="stripe.radar.early_fraud_warning.list",
    service="stripe",
    category="radar",
    description="List early fraud warnings",
    parameters={
        "charge": ParameterSchema(
            type="string",
            required=False,
            description="Filter by charge ID",
        ),
        "payment_intent": ParameterSchema(
            type="string",
            required=False,
            description="Filter by payment intent ID",
        ),
        "limit": ParameterSchema(
            type="integer",
            required=False,
            description="Maximum number to return",
            default=10,
        ),
    },
    returns={
        "data": ReturnFieldSchema(type="array", description="List of warnings"),
        "has_more": ReturnFieldSchema(type="boolean", description="More results"),
    },
    errors=[
        ErrorHint(
            error_code=ErrorCode.CREDENTIALS_MISSING,
            description="Stripe API key not configured",
            recovery_hint="Set STRIPE_SECRET_KEY environment variable",
        ),
    ],
    idempotent=True,
    has_side_effects=False,
)

# ============ REVIEWS ============

REVIEW_RETRIEVE = CapabilitySchema(
    capability_key="stripe.radar.review.retrieve",
    service="stripe",
    category="radar",
    description="Retrieve a Radar review",
    description_detailed=(
        "Retrieves a review generated by Radar when a payment is flagged "
        "for manual review based on your rules."
    ),
    parameters={
        "review_id": ParameterSchema(
            type="string",
            required=True,
            description="Review ID",
            example="prv_ABC123",
        ),
    },
    returns={
        "id": ReturnFieldSchema(type="string", description="Review ID"),
        "charge": ReturnFieldSchema(type="string", description="Charge ID"),
        "payment_intent": ReturnFieldSchema(type="string", description="PI ID"),
        "reason": ReturnFieldSchema(type="string", description="Review reason"),
        "open": ReturnFieldSchema(type="boolean", description="Is open"),
        "opened_reason": ReturnFieldSchema(type="string", description="Why opened"),
        "closed_reason": ReturnFieldSchema(type="string", description="Why closed"),
    },
    errors=[
        ErrorHint(
            error_code=ErrorCode.CREDENTIALS_MISSING,
            description="Stripe API key not configured",
            recovery_hint="Set STRIPE_SECRET_KEY environment variable",
        ),
    ],
    idempotent=True,
    has_side_effects=False,
)

REVIEW_APPROVE = CapabilitySchema(
    capability_key="stripe.radar.review.approve",
    service="stripe",
    category="radar",
    description="Approve a Radar review",
    description_detailed=(
        "Approves a payment that was placed in review. The payment will proceed."
    ),
    parameters={
        "review_id": ParameterSchema(
            type="string",
            required=True,
            description="Review ID to approve",
        ),
    },
    returns={
        "id": ReturnFieldSchema(type="string", description="Review ID"),
        "open": ReturnFieldSchema(type="boolean", description="Should be false"),
        "closed_reason": ReturnFieldSchema(type="string", description="Should be approved"),
    },
    errors=[
        ErrorHint(
            error_code=ErrorCode.VALIDATION_ERROR,
            description="Review already closed",
            recovery_hint="Only open reviews can be approved",
        ),
    ],
    idempotent=False,
    has_side_effects=True,
)

REVIEW_LIST = CapabilitySchema(
    capability_key="stripe.radar.review.list",
    service="stripe",
    category="radar",
    description="List Radar reviews",
    parameters={
        "limit": ParameterSchema(
            type="integer",
            required=False,
            description="Maximum number to return",
            default=10,
        ),
    },
    returns={
        "data": ReturnFieldSchema(type="array", description="List of reviews"),
        "has_more": ReturnFieldSchema(type="boolean", description="More results"),
    },
    errors=[
        ErrorHint(
            error_code=ErrorCode.CREDENTIALS_MISSING,
            description="Stripe API key not configured",
            recovery_hint="Set STRIPE_SECRET_KEY environment variable",
        ),
    ],
    idempotent=True,
    has_side_effects=False,
)

RADAR_SCHEMAS: dict[str, CapabilitySchema] = {
    "stripe.radar.early_fraud_warning.retrieve": EARLY_FRAUD_WARNING_RETRIEVE,
    "stripe.radar.early_fraud_warning.list": EARLY_FRAUD_WARNING_LIST,
    "stripe.radar.review.retrieve": REVIEW_RETRIEVE,
    "stripe.radar.review.approve": REVIEW_APPROVE,
    "stripe.radar.review.list": REVIEW_LIST,
}
