"""
Banking/Payments Capability Registry
Plaid, Ramp, Mercury, Brex, Chase
"""

from app.connectors.brex import BrexConnector
from app.connectors.chase import ChaseConnector
from app.connectors.mercury import MercuryConnector
from app.connectors.plaid import PlaidConnector
from app.connectors.ramp import RampConnector

# Initialize connectors
plaid_connector = PlaidConnector()
ramp_connector = RampConnector()
mercury_connector = MercuryConnector()
brex_connector = BrexConnector()
chase_connector = ChaseConnector()

BANKING_CAPABILITIES = {
    # ========== PLAID ==========
    "plaid.link.create": {
        "handler": plaid_connector.create_link_token,
        "tool_name": "plaid.create_link_token",
        "description": "Create Link token for Plaid",
        "requires_oauth": False,
        "service": "plaid",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "plaid.accesstoken.exchange": {
        "handler": plaid_connector.exchange_public_token,
        "tool_name": "plaid.exchange_public_token",
        "description": "Exchange public token for access token",
        "requires_oauth": False,
        "service": "plaid",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "plaid.transactions.sync": {
        "handler": plaid_connector.get_transactions_sync,
        "tool_name": "plaid.get_transactions_sync",
        "description": "Get transactions using sync (2025 recommended)",
        "requires_oauth": False,
        "service": "plaid",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "plaid.transactions.get": {
        "handler": plaid_connector.get_transactions_sync,
        "tool_name": "plaid.get_transactions_sync",
        "description": "Get transactions (legacy method - uses sync)",
        "requires_oauth": False,
        "service": "plaid",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "plaid.auth.get": {
        "handler": plaid_connector.get_auth,
        "tool_name": "plaid.get_auth",
        "description": "Get bank account numbers (with TANs support)",
        "requires_oauth": False,
        "service": "plaid",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "plaid.balance.get": {
        "handler": plaid_connector.get_balance,
        "tool_name": "plaid.get_balance",
        "description": "Get account balances",
        "requires_oauth": False,
        "service": "plaid",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "plaid.accounts.get": {
        "handler": plaid_connector.get_accounts,
        "tool_name": "plaid.get_accounts",
        "description": "Get linked accounts",
        "requires_oauth": False,
        "service": "plaid",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "plaid.identity.get": {
        "handler": plaid_connector.get_identity,
        "tool_name": "plaid.get_identity",
        "description": "Get identity information",
        "requires_oauth": False,
        "service": "plaid",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "plaid.transfer.create": {
        "handler": plaid_connector.create_transfer,
        "tool_name": "plaid.create_transfer",
        "description": "Create ACH transfer via Plaid",
        "requires_oauth": False,
        "service": "plaid",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "plaid.transfer.get": {
        "handler": plaid_connector.get_transfer,
        "tool_name": "plaid.get_transfer",
        "description": "Get transfer status",
        "requires_oauth": False,
        "service": "plaid",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "plaid.processor.token.create": {
        "handler": plaid_connector.create_processor_token,
        "tool_name": "plaid.create_processor_token",
        "description": "Create processor token for third-party",
        "requires_oauth": False,
        "service": "plaid",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    # ========== RAMP ==========
    "ramp.transaction.list": {
        "handler": ramp_connector.list_transactions,
        "tool_name": "ramp.list_transactions",
        "description": "List card transactions in Ramp",
        "requires_oauth": True,
        "service": "ramp",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "ramp.reimbursement.create": {
        "handler": ramp_connector.create_reimbursement,
        "tool_name": "ramp.create_reimbursement",
        "description": "Create expense reimbursement in Ramp",
        "requires_oauth": True,
        "service": "ramp",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "ramp.user.list": {
        "handler": ramp_connector.get_users,
        "tool_name": "ramp.get_users",
        "description": "Get users in Ramp",
        "requires_oauth": True,
        "service": "ramp",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    # ========== MERCURY ==========
    "mercury.account.list": {
        "handler": mercury_connector.list_accounts,
        "tool_name": "mercury.list_accounts",
        "description": "List Mercury banking accounts",
        "requires_oauth": False,
        "service": "mercury",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "mercury.transaction.get": {
        "handler": mercury_connector.get_transactions,
        "tool_name": "mercury.get_transactions",
        "description": "Get transactions from Mercury",
        "requires_oauth": False,
        "service": "mercury",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "mercury.payment.create": {
        "handler": mercury_connector.create_payment,
        "tool_name": "mercury.create_payment",
        "description": "Create ACH payment (100 free/month)",
        "requires_oauth": False,
        "service": "mercury",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "mercury.recipient.create": {
        "handler": mercury_connector.create_recipient,
        "tool_name": "mercury.create_recipient",
        "description": "Create payment recipient",
        "requires_oauth": False,
        "service": "mercury",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "mercury.recipient.list": {
        "handler": mercury_connector.list_recipients,
        "tool_name": "mercury.list_recipients",
        "description": "List payment recipients",
        "requires_oauth": False,
        "service": "mercury",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "mercury.wire.create": {
        "handler": mercury_connector.create_wire,
        "tool_name": "mercury.create_wire",
        "description": "Create wire transfer (domestic/international)",
        "requires_oauth": False,
        "service": "mercury",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    # ========== BREX ==========
    "brex.transaction.list": {
        "handler": brex_connector.list_transactions,
        "tool_name": "brex.list_transactions",
        "description": "List card transactions in Brex",
        "requires_oauth": True,
        "service": "brex",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "brex.expense.list": {
        "handler": brex_connector.list_expenses,
        "tool_name": "brex.list_expenses",
        "description": "List expenses with categories in Brex",
        "requires_oauth": True,
        "service": "brex",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "brex.card.virtual.create": {
        "handler": brex_connector.create_virtual_card,
        "tool_name": "brex.create_virtual_card",
        "description": "Create virtual card with spending limits",
        "requires_oauth": True,
        "service": "brex",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "brex.card.lock": {
        "handler": brex_connector.lock_card,
        "tool_name": "brex.lock_card",
        "description": "Lock a card in Brex",
        "requires_oauth": True,
        "service": "brex",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "brex.card.unlock": {
        "handler": brex_connector.unlock_card,
        "tool_name": "brex.unlock_card",
        "description": "Unlock a card in Brex",
        "requires_oauth": True,
        "service": "brex",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "brex.card.limit.update": {
        "handler": brex_connector.update_card_limit,
        "tool_name": "brex.update_card_limit",
        "description": "Update card spending limit",
        "requires_oauth": True,
        "service": "brex",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "brex.payment.create": {
        "handler": brex_connector.create_payment,
        "tool_name": "brex.create_payment",
        "description": "Create vendor payment in Brex",
        "requires_oauth": True,
        "service": "brex",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "brex.balance.get": {
        "handler": brex_connector.get_account_balance,
        "tool_name": "brex.get_account_balance",
        "description": "Get cash account balance",
        "requires_oauth": True,
        "service": "brex",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    # ========== CHASE/JPMORGAN ==========
    "chase.account.list": {
        "handler": chase_connector.list_accounts,
        "tool_name": "chase.list_accounts",
        "description": "List business banking accounts",
        "requires_oauth": True,
        "service": "chase",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "chase.balance.get": {
        "handler": chase_connector.get_account_balance,
        "tool_name": "chase.get_account_balance",
        "description": "Get account balance",
        "requires_oauth": True,
        "service": "chase",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "chase.transaction.get": {
        "handler": chase_connector.get_transactions,
        "tool_name": "chase.get_transactions",
        "description": "Get account transactions",
        "requires_oauth": True,
        "service": "chase",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "chase.ach.create": {
        "handler": chase_connector.create_ach_payment,
        "tool_name": "chase.create_ach_payment",
        "description": "Create ACH payment (free for business)",
        "requires_oauth": True,
        "service": "chase",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "chase.wire.create": {
        "handler": chase_connector.create_wire_payment,
        "tool_name": "chase.create_wire_payment",
        "description": "Create wire transfer (domestic/international)",
        "requires_oauth": True,
        "service": "chase",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "chase.payment.status": {
        "handler": chase_connector.get_payment_status,
        "tool_name": "chase.get_payment_status",
        "description": "Get payment status",
        "requires_oauth": True,
        "service": "chase",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "chase.payment.list": {
        "handler": chase_connector.list_payments,
        "tool_name": "chase.list_payments",
        "description": "List payment history",
        "requires_oauth": True,
        "service": "chase",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "chase.recipient.create": {
        "handler": chase_connector.create_recipient,
        "tool_name": "chase.create_recipient",
        "description": "Create payment recipient/beneficiary",
        "requires_oauth": True,
        "service": "chase",
        "credential_type": "customer",
        "supports_delegation": False,
    },
}
