"""E2B capability registry entries."""

from __future__ import annotations

from app.connectors.e2b_sandbox import E2BSandboxConnector

e2b_connector = E2BSandboxConnector()

E2B_CAPABILITIES = {
    "sandbox.ensure": {
        "handler": e2b_connector.ensure,
        "tool_name": "e2b.ensure",
        "description": "Create or reconnect to a long-lived sandbox for code and file work",
        "requires_oauth": False,
        "service": "e2b",
        "credential_type": None,
        "supports_delegation": False,
    },
    "sandbox.python.run": {
        "handler": e2b_connector.run_python,
        "tool_name": "e2b.run_python",
        "description": "Run Python code inside an isolated E2B sandbox",
        "requires_oauth": False,
        "service": "e2b",
        "credential_type": None,
        "supports_delegation": False,
    },
    "sandbox.python.run_background": {
        "handler": e2b_connector.run_python_background,
        "tool_name": "e2b.run_python_background",
        "description": "Start Python code inside an isolated E2B sandbox and leave it running",
        "requires_oauth": False,
        "service": "e2b",
        "credential_type": None,
        "supports_delegation": False,
    },
    "sandbox.bash.run": {
        "handler": e2b_connector.run_bash,
        "tool_name": "e2b.run_bash",
        "description": "Run a shell command inside an isolated E2B sandbox",
        "requires_oauth": False,
        "service": "e2b",
        "credential_type": None,
        "supports_delegation": False,
    },
    "sandbox.bash.run_background": {
        "handler": e2b_connector.run_bash_background,
        "tool_name": "e2b.run_bash_background",
        "description": "Start a shell command inside an isolated E2B sandbox and leave it running",
        "requires_oauth": False,
        "service": "e2b",
        "credential_type": None,
        "supports_delegation": False,
    },
    "sandbox.file.write": {
        "handler": e2b_connector.write_file,
        "tool_name": "e2b.write_file",
        "description": "Write text or base64-decoded bytes into an E2B sandbox file",
        "requires_oauth": False,
        "service": "e2b",
        "credential_type": None,
        "supports_delegation": False,
    },
    "sandbox.file.read": {
        "handler": e2b_connector.read_file,
        "tool_name": "e2b.read_file",
        "description": "Read text or base64-encoded bytes from an E2B sandbox file",
        "requires_oauth": False,
        "service": "e2b",
        "credential_type": None,
        "supports_delegation": False,
    },
    "sandbox.command.list": {
        "handler": e2b_connector.list_commands,
        "tool_name": "e2b.list_commands",
        "description": "List background commands that are still running inside an E2B sandbox",
        "requires_oauth": False,
        "service": "e2b",
        "credential_type": None,
        "supports_delegation": False,
    },
    "sandbox.command.kill": {
        "handler": e2b_connector.kill_command,
        "tool_name": "e2b.kill_command",
        "description": "Terminate a background command running inside an E2B sandbox",
        "requires_oauth": False,
        "service": "e2b",
        "credential_type": None,
        "supports_delegation": False,
    },
    "sandbox.pause": {
        "handler": e2b_connector.pause,
        "tool_name": "e2b.pause",
        "description": "Pause an E2B sandbox so the work can resume later",
        "requires_oauth": False,
        "service": "e2b",
        "credential_type": None,
        "supports_delegation": False,
    },
    "sandbox.timeout.set": {
        "handler": e2b_connector.set_timeout,
        "tool_name": "e2b.set_timeout",
        "description": "Update the timeout on a running E2B sandbox",
        "requires_oauth": False,
        "service": "e2b",
        "credential_type": None,
        "supports_delegation": False,
    },
    "sandbox.snapshot.create": {
        "handler": e2b_connector.create_snapshot,
        "tool_name": "e2b.create_snapshot",
        "description": "Create a reusable snapshot of the current E2B sandbox state",
        "requires_oauth": False,
        "service": "e2b",
        "credential_type": None,
        "supports_delegation": False,
    },
    "sandbox.get_info": {
        "handler": e2b_connector.get_info,
        "tool_name": "e2b.get_info",
        "description": "Inspect E2B sandbox lifecycle state and runtime metrics",
        "requires_oauth": False,
        "service": "e2b",
        "credential_type": None,
        "supports_delegation": False,
    },
    "artifact.xlsx.build": {
        "handler": e2b_connector.build_xlsx_artifact,
        "tool_name": "e2b.build_xlsx_artifact",
        "description": "Build a finance-friendly XLSX workbook inside an E2B sandbox",
        "requires_oauth": False,
        "service": "e2b",
        "credential_type": None,
        "supports_delegation": False,
    },
    "chart.render": {
        "handler": e2b_connector.render_chart,
        "tool_name": "e2b.render_chart",
        "description": "Render a chart artifact inside an E2B sandbox and return it as SVG",
        "requires_oauth": False,
        "service": "e2b",
        "credential_type": None,
        "supports_delegation": False,
    },
}

__all__ = ["E2B_CAPABILITIES"]
