"""
Google Workspace & Microsoft 365 & Dropbox Capability Registry
Google Drive, Google Calendar, Google Sheets
Microsoft Excel, Microsoft OneDrive, Microsoft Outlook Calendar
Dropbox file storage
"""

from app.connectors.dropbox import DropboxConnector
from app.connectors.google_calendar import GoogleCalendarConnector
from app.connectors.google_drive import GoogleDriveConnector
from app.connectors.google_sheets import GoogleSheetsConnector
from app.connectors.microsoft_excel import MicrosoftExcelConnector
from app.connectors.microsoft_onedrive import MicrosoftOneDriveConnector
from app.connectors.microsoft_outlook_calendar import MicrosoftOutlookCalendarConnector

# Initialize connectors
gdrive_connector = GoogleDriveConnector()
gcal_connector = GoogleCalendarConnector()
gsheets_connector = GoogleSheetsConnector()
excel_connector = MicrosoftExcelConnector()
onedrive_connector = MicrosoftOneDriveConnector()
outlook_cal_connector = MicrosoftOutlookCalendarConnector()
dropbox_connector = DropboxConnector()

GOOGLE_MICROSOFT_CAPABILITIES = {
    # ========== GOOGLE DRIVE ==========
    "gdrive.file.upload": {
        "handler": gdrive_connector.upload_file,
        "tool_name": "google_drive.upload_file",
        "description": "Upload file to Google Drive",
        "requires_oauth": True,
        "service": "google",
        "credential_type": "agent",
        "supports_delegation": True,
        "delegation_instructions": "Grant Aleq access to your Google Drive",
    },
    "gdrive.file.download": {
        "handler": gdrive_connector.download_file,
        "tool_name": "google_drive.download_file",
        "description": "Download file from Google Drive",
        "requires_oauth": True,
        "service": "google",
        "credential_type": "agent",
        "supports_delegation": True,
        "delegation_instructions": "Grant Aleq access to your Google Drive",
    },
    "gdrive.file.list": {
        "handler": gdrive_connector.list_files,
        "tool_name": "google_drive.list_files",
        "description": "List files in Google Drive folder",
        "requires_oauth": True,
        "service": "google",
        "credential_type": "agent",
        "supports_delegation": True,
        "delegation_instructions": "Grant Aleq access to your Google Drive",
    },
    "gdrive.folder.create": {
        "handler": gdrive_connector.create_folder,
        "tool_name": "google_drive.create_folder",
        "description": "Create folder in Google Drive",
        "requires_oauth": True,
        "service": "google",
        "credential_type": "agent",
        "supports_delegation": True,
        "delegation_instructions": "Grant Aleq access to your Google Drive",
    },
    "gdrive.file.metadata": {
        "handler": gdrive_connector.get_file_metadata,
        "tool_name": "google_drive.get_file_metadata",
        "description": "Get file metadata from Google Drive",
        "requires_oauth": True,
        "service": "google",
        "credential_type": "agent",
        "supports_delegation": True,
        "delegation_instructions": "Grant Aleq access to your Google Drive",
    },
    # ========== GOOGLE CALENDAR ==========
    "gcal.event.create": {
        "handler": gcal_connector.create_event,
        "tool_name": "google_calendar.create_event",
        "description": "Create calendar event in Google Calendar",
        "requires_oauth": True,
        "service": "google",
        "credential_type": "agent",
        "supports_delegation": True,
        "delegation_instructions": "Grant Aleq access to your Google Calendar",
    },
    "gcal.availability.check": {
        "handler": gcal_connector.check_availability,
        "tool_name": "google_calendar.check_availability",
        "description": "Check free/busy time for attendees in Google Calendar",
        "requires_oauth": True,
        "service": "google",
        "credential_type": "agent",
        "supports_delegation": True,
        "delegation_instructions": "Grant Aleq access to your Google Calendar",
    },
    "gcal.event.update": {
        "handler": gcal_connector.update_event,
        "tool_name": "google_calendar.update_event",
        "description": "Update calendar event in Google Calendar",
        "requires_oauth": True,
        "service": "google",
        "credential_type": "agent",
        "supports_delegation": True,
        "delegation_instructions": "Grant Aleq access to your Google Calendar",
    },
    "gcal.event.list": {
        "handler": gcal_connector.list_events,
        "tool_name": "google_calendar.list_events",
        "description": "List calendar events in Google Calendar",
        "requires_oauth": True,
        "service": "google",
        "credential_type": "agent",
        "supports_delegation": True,
        "delegation_instructions": "Grant Aleq access to your Google Calendar",
    },
    "gcal.event.cancel": {
        "handler": gcal_connector.cancel_event,
        "tool_name": "google_calendar.cancel_event",
        "description": "Cancel calendar event in Google Calendar",
        "requires_oauth": True,
        "service": "google",
        "credential_type": "agent",
        "supports_delegation": True,
        "delegation_instructions": "Grant Aleq access to your Google Calendar",
    },
    # ========== GOOGLE SHEETS ==========
    "gsheets.range.get": {
        "handler": gsheets_connector.get_range,
        "tool_name": "google_sheets.get_range",
        "description": "Get values from range in Google Sheets",
        "requires_oauth": True,
        "service": "google",
        "credential_type": "agent",
        "supports_delegation": True,
        "delegation_instructions": "Grant Aleq access to your Google Sheets",
    },
    "gsheets.range.update": {
        "handler": gsheets_connector.update_range,
        "tool_name": "google_sheets.update_range",
        "description": "Update values in range in Google Sheets",
        "requires_oauth": True,
        "service": "google",
        "credential_type": "agent",
        "supports_delegation": True,
        "delegation_instructions": "Grant Aleq access to your Google Sheets",
    },
    "gsheets.row.append": {
        "handler": gsheets_connector.append_row,
        "tool_name": "google_sheets.append_row",
        "description": "Append row to Google Sheets",
        "requires_oauth": True,
        "service": "google",
        "credential_type": "agent",
        "supports_delegation": True,
        "delegation_instructions": "Grant Aleq access to your Google Sheets",
    },
    "gsheets.sheet.create": {
        "handler": gsheets_connector.create_sheet,
        "tool_name": "google_sheets.create_sheet",
        "description": "Create new sheet in Google Sheets",
        "requires_oauth": True,
        "service": "google",
        "credential_type": "agent",
        "supports_delegation": True,
        "delegation_instructions": "Grant Aleq access to your Google Sheets",
    },
    "gsheets.batch.update": {
        "handler": gsheets_connector.batch_update,
        "tool_name": "google_sheets.batch_update",
        "description": "Perform batch updates in Google Sheets",
        "requires_oauth": True,
        "service": "google",
        "credential_type": "agent",
        "supports_delegation": True,
        "delegation_instructions": "Grant Aleq access to your Google Sheets",
    },
    "gsheets.range.clear": {
        "handler": gsheets_connector.clear_range,
        "tool_name": "google_sheets.clear_range",
        "description": "Clear values in range in Google Sheets",
        "requires_oauth": True,
        "service": "google",
        "credential_type": "agent",
        "supports_delegation": True,
        "delegation_instructions": "Grant Aleq access to your Google Sheets",
    },
    "gsheets.metadata.get": {
        "handler": gsheets_connector.get_sheet_metadata,
        "tool_name": "google_sheets.get_sheet_metadata",
        "description": "Get metadata about Google Spreadsheet",
        "requires_oauth": True,
        "service": "google",
        "credential_type": "agent",
        "supports_delegation": True,
        "delegation_instructions": "Grant Aleq access to your Google Sheets",
    },
    # ========== MICROSOFT EXCEL ==========
    "excel.range.get": {
        "handler": excel_connector.get_range,
        "tool_name": "microsoft_excel.get_range",
        "description": "Get values from range in Excel via Microsoft Graph",
        "requires_oauth": True,
        "service": "microsoft",
        "credential_type": "agent",
        "supports_delegation": True,
        "delegation_instructions": "Grant Aleq access to your Microsoft Excel",
    },
    "excel.range.update": {
        "handler": excel_connector.update_range,
        "tool_name": "microsoft_excel.update_range",
        "description": "Update values in range in Excel via Microsoft Graph",
        "requires_oauth": True,
        "service": "microsoft",
        "credential_type": "agent",
        "supports_delegation": True,
        "delegation_instructions": "Grant Aleq access to your Microsoft Excel",
    },
    "excel.row.append": {
        "handler": excel_connector.append_row,
        "tool_name": "microsoft_excel.append_row",
        "description": "Append row to Excel worksheet via Microsoft Graph",
        "requires_oauth": True,
        "service": "microsoft",
        "credential_type": "agent",
        "supports_delegation": True,
        "delegation_instructions": "Grant Aleq access to your Microsoft Excel",
    },
    "excel.worksheet.create": {
        "handler": excel_connector.create_worksheet,
        "tool_name": "microsoft_excel.create_worksheet",
        "description": "Create new worksheet in Excel via Microsoft Graph",
        "requires_oauth": True,
        "service": "microsoft",
        "credential_type": "agent",
        "supports_delegation": True,
        "delegation_instructions": "Grant Aleq access to your Microsoft Excel",
    },
    "excel.worksheet.list": {
        "handler": excel_connector.get_worksheets,
        "tool_name": "microsoft_excel.get_worksheets",
        "description": "List worksheets in Excel workbook via Microsoft Graph",
        "requires_oauth": True,
        "service": "microsoft",
        "credential_type": "agent",
        "supports_delegation": True,
        "delegation_instructions": "Grant Aleq access to your Microsoft Excel",
    },
    "excel.table.create": {
        "handler": excel_connector.create_table,
        "tool_name": "microsoft_excel.create_table",
        "description": "Create table in Excel worksheet via Microsoft Graph",
        "requires_oauth": True,
        "service": "microsoft",
        "credential_type": "agent",
        "supports_delegation": True,
        "delegation_instructions": "Grant Aleq access to your Microsoft Excel",
    },
    # ========== MICROSOFT ONEDRIVE ==========
    "onedrive.file.upload": {
        "handler": onedrive_connector.upload_file,
        "tool_name": "microsoft_onedrive.upload_file",
        "description": "Upload file to OneDrive via Microsoft Graph",
        "requires_oauth": True,
        "service": "microsoft",
        "credential_type": "agent",
        "supports_delegation": True,
        "delegation_instructions": "Grant Aleq access to your Microsoft OneDrive",
    },
    "onedrive.file.download": {
        "handler": onedrive_connector.download_file,
        "tool_name": "microsoft_onedrive.download_file",
        "description": "Download file from OneDrive via Microsoft Graph",
        "requires_oauth": True,
        "service": "microsoft",
        "credential_type": "agent",
        "supports_delegation": True,
        "delegation_instructions": "Grant Aleq access to your Microsoft OneDrive",
    },
    "onedrive.file.list": {
        "handler": onedrive_connector.list_files,
        "tool_name": "microsoft_onedrive.list_files",
        "description": "List files in OneDrive folder via Microsoft Graph",
        "requires_oauth": True,
        "service": "microsoft",
        "credential_type": "agent",
        "supports_delegation": True,
        "delegation_instructions": "Grant Aleq access to your Microsoft OneDrive",
    },
    "onedrive.folder.create": {
        "handler": onedrive_connector.create_folder,
        "tool_name": "microsoft_onedrive.create_folder",
        "description": "Create folder in OneDrive via Microsoft Graph",
        "requires_oauth": True,
        "service": "microsoft",
        "credential_type": "agent",
        "supports_delegation": True,
        "delegation_instructions": "Grant Aleq access to your Microsoft OneDrive",
    },
    "onedrive.file.metadata": {
        "handler": onedrive_connector.get_file_metadata,
        "tool_name": "microsoft_onedrive.get_file_metadata",
        "description": "Get file metadata from OneDrive via Microsoft Graph",
        "requires_oauth": True,
        "service": "microsoft",
        "credential_type": "agent",
        "supports_delegation": True,
        "delegation_instructions": "Grant Aleq access to your Microsoft OneDrive",
    },
    # ========== MICROSOFT OUTLOOK CALENDAR ==========
    "outlook.event.create": {
        "handler": outlook_cal_connector.create_event,
        "tool_name": "microsoft_outlook_calendar.create_event",
        "description": "Create calendar event in Outlook Calendar via Microsoft Graph",
        "requires_oauth": True,
        "service": "microsoft",
        "credential_type": "agent",
        "supports_delegation": True,
        "delegation_instructions": "Grant Aleq access to your Outlook Calendar",
    },
    "outlook.availability.check": {
        "handler": outlook_cal_connector.check_availability,
        "tool_name": "microsoft_outlook_calendar.check_availability",
        "description": "Check free/busy schedule in Outlook Calendar via Microsoft Graph",
        "requires_oauth": True,
        "service": "microsoft",
        "credential_type": "agent",
        "supports_delegation": True,
        "delegation_instructions": "Grant Aleq access to your Outlook Calendar",
    },
    "outlook.event.update": {
        "handler": outlook_cal_connector.update_event,
        "tool_name": "microsoft_outlook_calendar.update_event",
        "description": "Update calendar event in Outlook Calendar via Microsoft Graph",
        "requires_oauth": True,
        "service": "microsoft",
        "credential_type": "agent",
        "supports_delegation": True,
        "delegation_instructions": "Grant Aleq access to your Outlook Calendar",
    },
    "outlook.event.list": {
        "handler": outlook_cal_connector.list_events,
        "tool_name": "microsoft_outlook_calendar.list_events",
        "description": "List calendar events in Outlook Calendar via Microsoft Graph",
        "requires_oauth": True,
        "service": "microsoft",
        "credential_type": "agent",
        "supports_delegation": True,
        "delegation_instructions": "Grant Aleq access to your Outlook Calendar",
    },
    "outlook.event.cancel": {
        "handler": outlook_cal_connector.cancel_event,
        "tool_name": "microsoft_outlook_calendar.cancel_event",
        "description": "Cancel calendar event in Outlook Calendar via Microsoft Graph",
        "requires_oauth": True,
        "service": "microsoft",
        "credential_type": "agent",
        "supports_delegation": True,
        "delegation_instructions": "Grant Aleq access to your Outlook Calendar",
    },
    # ========== DROPBOX ==========
    "dropbox.file.upload": {
        "handler": dropbox_connector.upload_file,
        "tool_name": "dropbox.upload_file",
        "description": "Upload file to Dropbox",
        "requires_oauth": True,
        "service": "dropbox",
        "credential_type": "agent",
        "supports_delegation": True,
        "delegation_instructions": "Grant Aleq access to your Dropbox",
    },
    "dropbox.file.download": {
        "handler": dropbox_connector.download_file,
        "tool_name": "dropbox.download_file",
        "description": "Download file from Dropbox",
        "requires_oauth": True,
        "service": "dropbox",
        "credential_type": "agent",
        "supports_delegation": True,
        "delegation_instructions": "Grant Aleq access to your Dropbox",
    },
    "dropbox.file.list": {
        "handler": dropbox_connector.list_files,
        "tool_name": "dropbox.list_files",
        "description": "List files in Dropbox folder",
        "requires_oauth": True,
        "service": "dropbox",
        "credential_type": "agent",
        "supports_delegation": True,
        "delegation_instructions": "Grant Aleq access to your Dropbox",
    },
    "dropbox.folder.create": {
        "handler": dropbox_connector.create_folder,
        "tool_name": "dropbox.create_folder",
        "description": "Create folder in Dropbox",
        "requires_oauth": True,
        "service": "dropbox",
        "credential_type": "agent",
        "supports_delegation": True,
        "delegation_instructions": "Grant Aleq access to your Dropbox",
    },
    "dropbox.file.metadata": {
        "handler": dropbox_connector.get_file_metadata,
        "tool_name": "dropbox.get_file_metadata",
        "description": "Get file metadata from Dropbox",
        "requires_oauth": True,
        "service": "dropbox",
        "credential_type": "agent",
        "supports_delegation": True,
        "delegation_instructions": "Grant Aleq access to your Dropbox",
    },
}
