"""
Trading/Brokerage Capability Registry
Interactive Brokers, Charles Schwab
"""

from app.connectors.ibkr import IBKRConnector
from app.connectors.schwab import SchwabConnector

# Initialize connectors
ibkr_connector = IBKRConnector()
schwab_connector = SchwabConnector()

TRADING_CAPABILITIES = {
    # ========== INTERACTIVE BROKERS ==========
    "ibkr.session.auth": {
        "handler": ibkr_connector.authenticate_session,
        "tool_name": "ibkr.authenticate_session",
        "description": "Authenticate brokerage session",
        "requires_oauth": False,
        "service": "ibkr",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "ibkr.account.list": {
        "handler": ibkr_connector.get_accounts,
        "tool_name": "ibkr.get_accounts",
        "description": "Get list of trading accounts",
        "requires_oauth": False,
        "service": "ibkr",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "ibkr.account.summary": {
        "handler": ibkr_connector.get_account_summary,
        "tool_name": "ibkr.get_account_summary",
        "description": "Get account summary with balances",
        "requires_oauth": False,
        "service": "ibkr",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "ibkr.position.get": {
        "handler": ibkr_connector.get_positions,
        "tool_name": "ibkr.get_positions",
        "description": "Get portfolio positions",
        "requires_oauth": False,
        "service": "ibkr",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "ibkr.pnl.get": {
        "handler": ibkr_connector.get_pnl,
        "tool_name": "ibkr.get_pnl",
        "description": "Get profit and loss",
        "requires_oauth": False,
        "service": "ibkr",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "ibkr.marketdata.get": {
        "handler": ibkr_connector.get_market_data,
        "tool_name": "ibkr.get_market_data",
        "description": "Get market data snapshot",
        "requires_oauth": False,
        "service": "ibkr",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "ibkr.order.place": {
        "handler": ibkr_connector.place_order,
        "tool_name": "ibkr.place_order",
        "description": "Place trading order",
        "requires_oauth": False,
        "service": "ibkr",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "ibkr.order.modify": {
        "handler": ibkr_connector.modify_order,
        "tool_name": "ibkr.modify_order",
        "description": "Modify existing order",
        "requires_oauth": False,
        "service": "ibkr",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "ibkr.order.cancel": {
        "handler": ibkr_connector.cancel_order,
        "tool_name": "ibkr.cancel_order",
        "description": "Cancel order",
        "requires_oauth": False,
        "service": "ibkr",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "ibkr.order.list": {
        "handler": ibkr_connector.get_orders,
        "tool_name": "ibkr.get_orders",
        "description": "Get live orders",
        "requires_oauth": False,
        "service": "ibkr",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "ibkr.trade.list": {
        "handler": ibkr_connector.get_trades,
        "tool_name": "ibkr.get_trades",
        "description": "Get trade history",
        "requires_oauth": False,
        "service": "ibkr",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "ibkr.execution.list": {
        "handler": ibkr_connector.get_executions,
        "tool_name": "ibkr.get_executions",
        "description": "Get execution details",
        "requires_oauth": False,
        "service": "ibkr",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "ibkr.contract.search": {
        "handler": ibkr_connector.search_contract,
        "tool_name": "ibkr.search_contract",
        "description": "Search for contracts by symbol",
        "requires_oauth": False,
        "service": "ibkr",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "ibkr.contract.get": {
        "handler": ibkr_connector.get_contract_details,
        "tool_name": "ibkr.get_contract_details",
        "description": "Get contract details by conid",
        "requires_oauth": False,
        "service": "ibkr",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "ibkr.portfolio.allocation": {
        "handler": ibkr_connector.get_portfolio_allocation,
        "tool_name": "ibkr.get_portfolio_allocation",
        "description": "Get portfolio allocation by sector/asset class",
        "requires_oauth": False,
        "service": "ibkr",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    # ========== CHARLES SCHWAB ==========
    "schwab.account.list": {
        "handler": schwab_connector.get_accounts,
        "tool_name": "schwab.get_accounts",
        "description": "Get all linked accounts",
        "requires_oauth": True,
        "service": "schwab",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "schwab.account.get": {
        "handler": schwab_connector.get_account,
        "tool_name": "schwab.get_account",
        "description": "Get account details with positions",
        "requires_oauth": True,
        "service": "schwab",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "schwab.position.get": {
        "handler": schwab_connector.get_positions,
        "tool_name": "schwab.get_positions",
        "description": "Get positions for account",
        "requires_oauth": True,
        "service": "schwab",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "schwab.order.place": {
        "handler": schwab_connector.place_order,
        "tool_name": "schwab.place_order",
        "description": "Place trading order",
        "requires_oauth": True,
        "service": "schwab",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "schwab.order.list": {
        "handler": schwab_connector.get_orders,
        "tool_name": "schwab.get_orders",
        "description": "Get orders for account",
        "requires_oauth": True,
        "service": "schwab",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "schwab.order.cancel": {
        "handler": schwab_connector.cancel_order,
        "tool_name": "schwab.cancel_order",
        "description": "Cancel order",
        "requires_oauth": True,
        "service": "schwab",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "schwab.order.replace": {
        "handler": schwab_connector.replace_order,
        "tool_name": "schwab.replace_order",
        "description": "Replace/modify existing order",
        "requires_oauth": True,
        "service": "schwab",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "schwab.quote.get": {
        "handler": schwab_connector.get_quote,
        "tool_name": "schwab.get_quote",
        "description": "Get quote for single symbol",
        "requires_oauth": True,
        "service": "schwab",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "schwab.quote.list": {
        "handler": schwab_connector.get_quotes,
        "tool_name": "schwab.get_quotes",
        "description": "Get quotes for multiple symbols",
        "requires_oauth": True,
        "service": "schwab",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "schwab.pricehistory.get": {
        "handler": schwab_connector.get_price_history,
        "tool_name": "schwab.get_price_history",
        "description": "Get price history for symbol",
        "requires_oauth": True,
        "service": "schwab",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "schwab.optionchain.get": {
        "handler": schwab_connector.get_option_chain,
        "tool_name": "schwab.get_option_chain",
        "description": "Get option chain for symbol",
        "requires_oauth": True,
        "service": "schwab",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "schwab.transaction.list": {
        "handler": schwab_connector.get_transactions,
        "tool_name": "schwab.get_transactions",
        "description": "Get transaction history",
        "requires_oauth": True,
        "service": "schwab",
        "credential_type": "customer",
        "supports_delegation": False,
    },
}
