"""
Plaid Capability Registry
"""

from app.connectors.plaid import PlaidConnector

plaid_connector = PlaidConnector()

PLAID_CAPABILITIES = {
    "plaid.link.create": {
        "handler": plaid_connector.create_link_token,
        "tool_name": "plaid.create_link_token",
        "description": "Create Link token for Plaid",
        "requires_oauth": False,
        "service": "plaid",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "plaid.accesstoken.exchange": {
        "handler": plaid_connector.exchange_public_token,
        "tool_name": "plaid.exchange_public_token",
        "description": "Exchange public token for access token",
        "requires_oauth": False,
        "service": "plaid",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "plaid.transactions.sync": {
        "handler": plaid_connector.get_transactions_sync,
        "tool_name": "plaid.get_transactions_sync",
        "description": "Get transactions using sync (2025 recommended)",
        "requires_oauth": False,
        "service": "plaid",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "plaid.transactions.get": {
        "handler": plaid_connector.get_transactions_sync,
        "tool_name": "plaid.get_transactions_sync",
        "description": "Get transactions (legacy method - uses sync)",
        "requires_oauth": False,
        "service": "plaid",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "plaid.auth.get": {
        "handler": plaid_connector.get_auth,
        "tool_name": "plaid.get_auth",
        "description": "Get bank account numbers (with TANs support)",
        "requires_oauth": False,
        "service": "plaid",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "plaid.balance.get": {
        "handler": plaid_connector.get_balance,
        "tool_name": "plaid.get_balance",
        "description": "Get account balances",
        "requires_oauth": False,
        "service": "plaid",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "plaid.accounts.get": {
        "handler": plaid_connector.get_accounts,
        "tool_name": "plaid.get_accounts",
        "description": "Get linked accounts",
        "requires_oauth": False,
        "service": "plaid",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "plaid.identity.get": {
        "handler": plaid_connector.get_identity,
        "tool_name": "plaid.get_identity",
        "description": "Get identity information",
        "requires_oauth": False,
        "service": "plaid",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "plaid.transfer.create": {
        "handler": plaid_connector.create_transfer,
        "tool_name": "plaid.create_transfer",
        "description": "Create ACH transfer via Plaid",
        "requires_oauth": False,
        "service": "plaid",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "plaid.transfer.get": {
        "handler": plaid_connector.get_transfer,
        "tool_name": "plaid.get_transfer",
        "description": "Get transfer status",
        "requires_oauth": False,
        "service": "plaid",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "plaid.processor.token.create": {
        "handler": plaid_connector.create_processor_token,
        "tool_name": "plaid.create_processor_token",
        "description": "Create processor token for third-party",
        "requires_oauth": False,
        "service": "plaid",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    # ===== NEW PLAID CAPABILITIES =====
    "plaid.liabilities.get": {
        "handler": plaid_connector.get_liabilities,
        "tool_name": "plaid.get_liabilities",
        "description": "Get liabilities (credit cards, student loans, mortgages)",
        "requires_oauth": False,
        "service": "plaid",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "plaid.investments.holdings": {
        "handler": plaid_connector.get_investment_holdings,
        "tool_name": "plaid.get_investment_holdings",
        "description": "Get investment holdings",
        "requires_oauth": False,
        "service": "plaid",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "plaid.investments.transactions": {
        "handler": plaid_connector.get_investment_transactions,
        "tool_name": "plaid.get_investment_transactions",
        "description": "Get investment transactions",
        "requires_oauth": False,
        "service": "plaid",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "plaid.transfer.list": {
        "handler": plaid_connector.list_transfers,
        "tool_name": "plaid.list_transfers",
        "description": "List transfers",
        "requires_oauth": False,
        "service": "plaid",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "plaid.institution.get": {
        "handler": plaid_connector.get_institution,
        "tool_name": "plaid.get_institution",
        "description": "Get institution details by ID",
        "requires_oauth": False,
        "service": "plaid",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "plaid.categories.get": {
        "handler": plaid_connector.get_categories,
        "tool_name": "plaid.get_categories",
        "description": "Get all Plaid transaction categories",
        "requires_oauth": False,
        "service": "plaid",
        "credential_type": "customer",
        "supports_delegation": False,
    },
}
