"""
Asana Capability Registry
"""

from app.connectors.asana import AsanaConnector

# Initialize connector
asana_connector = AsanaConnector()

ASANA_CAPABILITIES = {
    # ========== ASANA ==========
    "asana.task.create": {
        "handler": asana_connector.create_task,
        "tool_name": "asana.create_task",
        "description": "Create task in Asana",
        "requires_oauth": True,
        "service": "asana",
        "credential_type": "agent",
        "supports_delegation": True,
        "delegation_instructions": "Grant Aleq access to your Asana workspace",
    },
    "asana.task.update": {
        "handler": asana_connector.update_task,
        "tool_name": "asana.update_task",
        "description": "Update existing task",
        "requires_oauth": True,
        "service": "asana",
        "credential_type": "agent",
        "supports_delegation": True,
        "delegation_instructions": "Grant Aleq access to your Asana workspace",
    },
    "asana.task.get": {
        "handler": asana_connector.get_task,
        "tool_name": "asana.get_task",
        "description": "Get task details",
        "requires_oauth": True,
        "service": "asana",
        "credential_type": "agent",
        "supports_delegation": True,
        "delegation_instructions": "Grant Aleq access to your Asana workspace",
    },
    "asana.task.list": {
        "handler": asana_connector.list_tasks,
        "tool_name": "asana.list_tasks",
        "description": "List tasks in project",
        "requires_oauth": True,
        "service": "asana",
        "credential_type": "agent",
        "supports_delegation": True,
        "delegation_instructions": "Grant Aleq access to your Asana workspace",
    },
    "asana.project.create": {
        "handler": asana_connector.create_project,
        "tool_name": "asana.create_project",
        "description": "Create project in Asana",
        "requires_oauth": True,
        "service": "asana",
        "credential_type": "agent",
        "supports_delegation": True,
        "delegation_instructions": "Grant Aleq access to your Asana workspace",
    },
    "asana.project.get": {
        "handler": asana_connector.get_project,
        "tool_name": "asana.get_project",
        "description": "Get project details",
        "requires_oauth": True,
        "service": "asana",
        "credential_type": "agent",
        "supports_delegation": True,
        "delegation_instructions": "Grant Aleq access to your Asana workspace",
    },
    "asana.project.list": {
        "handler": asana_connector.list_projects,
        "tool_name": "asana.list_projects",
        "description": "List projects in workspace",
        "requires_oauth": True,
        "service": "asana",
        "credential_type": "agent",
        "supports_delegation": True,
        "delegation_instructions": "Grant Aleq access to your Asana workspace",
    },
    "asana.customfield.add": {
        "handler": asana_connector.add_custom_field_to_project,
        "tool_name": "asana.add_custom_field_to_project",
        "description": "Add custom field to project",
        "requires_oauth": True,
        "service": "asana",
        "credential_type": "agent",
        "supports_delegation": True,
        "delegation_instructions": "Grant Aleq access to your Asana workspace",
    },
    "asana.customfield.update": {
        "handler": asana_connector.update_task_custom_field,
        "tool_name": "asana.update_task_custom_field",
        "description": "Update custom field on task",
        "requires_oauth": True,
        "service": "asana",
        "credential_type": "agent",
        "supports_delegation": True,
        "delegation_instructions": "Grant Aleq access to your Asana workspace",
    },
    "asana.section.create": {
        "handler": asana_connector.create_section,
        "tool_name": "asana.create_section",
        "description": "Create section in project",
        "requires_oauth": True,
        "service": "asana",
        "credential_type": "agent",
        "supports_delegation": True,
        "delegation_instructions": "Grant Aleq access to your Asana workspace",
    },
    "asana.section.addtask": {
        "handler": asana_connector.add_task_to_section,
        "tool_name": "asana.add_task_to_section",
        "description": "Add task to section",
        "requires_oauth": True,
        "service": "asana",
        "credential_type": "agent",
        "supports_delegation": True,
        "delegation_instructions": "Grant Aleq access to your Asana workspace",
    },
    "asana.attachment.upload": {
        "handler": asana_connector.upload_attachment,
        "tool_name": "asana.upload_attachment",
        "description": "Upload attachment to task",
        "requires_oauth": True,
        "service": "asana",
        "credential_type": "agent",
        "supports_delegation": True,
        "delegation_instructions": "Grant Aleq access to your Asana workspace",
    },
}
