"""
HubSpot CRM Capability Registry
"""

from app.connectors.hubspot import HubSpotConnector

# Initialize connector
hubspot_connector = HubSpotConnector()

HUBSPOT_CAPABILITIES = {
    # ========== HUBSPOT CONTACTS ==========
    "crm.contact.create": {
        "handler": hubspot_connector.create_contact,
        "tool_name": "hubspot.create_contact",
        "description": "Create a contact in HubSpot CRM",
        "requires_oauth": True,
        "service": "hubspot",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "crm.contact.get": {
        "handler": hubspot_connector.get_contact,
        "tool_name": "hubspot.get_contact",
        "description": "Get contact details from HubSpot CRM",
        "requires_oauth": True,
        "service": "hubspot",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "crm.contact.list": {
        "handler": hubspot_connector.list_contacts,
        "tool_name": "hubspot.list_contacts",
        "description": "List contacts from HubSpot CRM",
        "requires_oauth": True,
        "service": "hubspot",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "crm.contact.update": {
        "handler": hubspot_connector.update_contact,
        "tool_name": "hubspot.update_contact",
        "description": "Update a contact in HubSpot CRM",
        "requires_oauth": True,
        "service": "hubspot",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "crm.contact.delete": {
        "handler": hubspot_connector.delete_contact,
        "tool_name": "hubspot.delete_contact",
        "description": "Delete a contact from HubSpot CRM",
        "requires_oauth": True,
        "service": "hubspot",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "crm.contact.search": {
        "handler": hubspot_connector.search_contacts,
        "tool_name": "hubspot.search_contacts",
        "description": "Search contacts in HubSpot CRM",
        "requires_oauth": True,
        "service": "hubspot",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    # ========== HUBSPOT DEALS ==========
    "crm.deal.create": {
        "handler": hubspot_connector.create_deal,
        "tool_name": "hubspot.create_deal",
        "description": "Create a deal in HubSpot CRM",
        "requires_oauth": True,
        "service": "hubspot",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "crm.deal.get": {
        "handler": hubspot_connector.get_deal,
        "tool_name": "hubspot.get_deal",
        "description": "Get deal details from HubSpot CRM",
        "requires_oauth": True,
        "service": "hubspot",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "crm.deal.list": {
        "handler": hubspot_connector.list_deals,
        "tool_name": "hubspot.list_deals",
        "description": "List deals from HubSpot CRM",
        "requires_oauth": True,
        "service": "hubspot",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "crm.deal.update": {
        "handler": hubspot_connector.update_deal,
        "tool_name": "hubspot.update_deal",
        "description": "Update a deal in HubSpot CRM",
        "requires_oauth": True,
        "service": "hubspot",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "crm.deal.delete": {
        "handler": hubspot_connector.delete_deal,
        "tool_name": "hubspot.delete_deal",
        "description": "Delete a deal from HubSpot CRM",
        "requires_oauth": True,
        "service": "hubspot",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "crm.deal.search": {
        "handler": hubspot_connector.search_deals,
        "tool_name": "hubspot.search_deals",
        "description": "Search deals in HubSpot CRM",
        "requires_oauth": True,
        "service": "hubspot",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    # ========== HUBSPOT COMPANIES ==========
    "crm.company.create": {
        "handler": hubspot_connector.create_company,
        "tool_name": "hubspot.create_company",
        "description": "Create a company in HubSpot CRM",
        "requires_oauth": True,
        "service": "hubspot",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "crm.company.get": {
        "handler": hubspot_connector.get_company,
        "tool_name": "hubspot.get_company",
        "description": "Get company details from HubSpot CRM",
        "requires_oauth": True,
        "service": "hubspot",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "crm.company.list": {
        "handler": hubspot_connector.list_companies,
        "tool_name": "hubspot.list_companies",
        "description": "List companies from HubSpot CRM",
        "requires_oauth": True,
        "service": "hubspot",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "crm.company.update": {
        "handler": hubspot_connector.update_company,
        "tool_name": "hubspot.update_company",
        "description": "Update a company in HubSpot CRM",
        "requires_oauth": True,
        "service": "hubspot",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "crm.company.delete": {
        "handler": hubspot_connector.delete_company,
        "tool_name": "hubspot.delete_company",
        "description": "Delete a company from HubSpot CRM",
        "requires_oauth": True,
        "service": "hubspot",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "crm.company.search": {
        "handler": hubspot_connector.search_companies,
        "tool_name": "hubspot.search_companies",
        "description": "Search companies in HubSpot CRM",
        "requires_oauth": True,
        "service": "hubspot",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    # ========== HUBSPOT TICKETS ==========
    "crm.ticket.create": {
        "handler": hubspot_connector.create_ticket,
        "tool_name": "hubspot.create_ticket",
        "description": "Create a ticket in HubSpot",
        "requires_oauth": True,
        "service": "hubspot",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "crm.ticket.get": {
        "handler": hubspot_connector.get_ticket,
        "tool_name": "hubspot.get_ticket",
        "description": "Get ticket details from HubSpot",
        "requires_oauth": True,
        "service": "hubspot",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "crm.ticket.list": {
        "handler": hubspot_connector.list_tickets,
        "tool_name": "hubspot.list_tickets",
        "description": "List tickets from HubSpot",
        "requires_oauth": True,
        "service": "hubspot",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "crm.ticket.update": {
        "handler": hubspot_connector.update_ticket,
        "tool_name": "hubspot.update_ticket",
        "description": "Update a ticket in HubSpot",
        "requires_oauth": True,
        "service": "hubspot",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "crm.ticket.delete": {
        "handler": hubspot_connector.delete_ticket,
        "tool_name": "hubspot.delete_ticket",
        "description": "Delete a ticket from HubSpot",
        "requires_oauth": True,
        "service": "hubspot",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "crm.ticket.search": {
        "handler": hubspot_connector.search_tickets,
        "tool_name": "hubspot.search_tickets",
        "description": "Search tickets in HubSpot",
        "requires_oauth": True,
        "service": "hubspot",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    # ========== HUBSPOT ASSOCIATIONS ==========
    "crm.association.create": {
        "handler": hubspot_connector.create_association,
        "tool_name": "hubspot.create_association",
        "description": "Create an association between two CRM objects",
        "requires_oauth": True,
        "service": "hubspot",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "crm.association.list": {
        "handler": hubspot_connector.list_associations,
        "tool_name": "hubspot.list_associations",
        "description": "List associations for a CRM object",
        "requires_oauth": True,
        "service": "hubspot",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "crm.association.delete": {
        "handler": hubspot_connector.delete_association,
        "tool_name": "hubspot.delete_association",
        "description": "Delete an association between two CRM objects",
        "requires_oauth": True,
        "service": "hubspot",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    # ========== HUBSPOT PIPELINES ==========
    "crm.pipeline.list": {
        "handler": hubspot_connector.list_pipelines,
        "tool_name": "hubspot.list_pipelines",
        "description": "List pipelines for an object type",
        "requires_oauth": True,
        "service": "hubspot",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "crm.pipeline.get": {
        "handler": hubspot_connector.get_pipeline,
        "tool_name": "hubspot.get_pipeline",
        "description": "Get pipeline details with stages",
        "requires_oauth": True,
        "service": "hubspot",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "crm.pipeline.stages": {
        "handler": hubspot_connector.list_pipeline_stages,
        "tool_name": "hubspot.list_pipeline_stages",
        "description": "List stages for a specific pipeline",
        "requires_oauth": True,
        "service": "hubspot",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    # ========== HUBSPOT OWNERS ==========
    "crm.owner.list": {
        "handler": hubspot_connector.list_owners,
        "tool_name": "hubspot.list_owners",
        "description": "List owners in HubSpot",
        "requires_oauth": True,
        "service": "hubspot",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "crm.owner.get": {
        "handler": hubspot_connector.get_owner,
        "tool_name": "hubspot.get_owner",
        "description": "Get owner details from HubSpot",
        "requires_oauth": True,
        "service": "hubspot",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    # ========== HUBSPOT NOTES ==========
    "crm.note.create": {
        "handler": hubspot_connector.create_note,
        "tool_name": "hubspot.create_note",
        "description": "Create a note in HubSpot",
        "requires_oauth": True,
        "service": "hubspot",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "crm.note.list": {
        "handler": hubspot_connector.list_notes,
        "tool_name": "hubspot.list_notes",
        "description": "List notes from HubSpot",
        "requires_oauth": True,
        "service": "hubspot",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "crm.note.get": {
        "handler": hubspot_connector.get_note,
        "tool_name": "hubspot.get_note",
        "description": "Get note details from HubSpot",
        "requires_oauth": True,
        "service": "hubspot",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    # ========== HUBSPOT PROPERTIES ==========
    "crm.property.list": {
        "handler": hubspot_connector.list_properties,
        "tool_name": "hubspot.list_properties",
        "description": "List properties for an object type",
        "requires_oauth": True,
        "service": "hubspot",
        "credential_type": "customer",
        "supports_delegation": False,
    },
}
