"""
HubSpot CRM Capability Registry
"""

from app.connectors.hubspot import HubSpotConnector

# Initialize connector
hubspot_connector = HubSpotConnector()

HUBSPOT_CAPABILITIES = {
    # ========== HUBSPOT CONTACTS ==========
    "crm.contact.create": {
        "handler": hubspot_connector.create_contact,
        "tool_name": "hubspot.create_contact",
        "description": "Create a contact in HubSpot CRM",
        "requires_oauth": True,
        "service": "hubspot",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "crm.contact.get": {
        "handler": hubspot_connector.get_contact,
        "tool_name": "hubspot.get_contact",
        "description": "Get contact details from HubSpot CRM",
        "requires_oauth": True,
        "service": "hubspot",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "crm.contact.list": {
        "handler": hubspot_connector.list_contacts,
        "tool_name": "hubspot.list_contacts",
        "description": "List contacts from HubSpot CRM",
        "requires_oauth": True,
        "service": "hubspot",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "crm.contact.update": {
        "handler": hubspot_connector.update_contact,
        "tool_name": "hubspot.update_contact",
        "description": "Update a contact in HubSpot CRM",
        "requires_oauth": True,
        "service": "hubspot",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "crm.contact.delete": {
        "handler": hubspot_connector.delete_contact,
        "tool_name": "hubspot.delete_contact",
        "description": "Delete a contact from HubSpot CRM",
        "requires_oauth": True,
        "service": "hubspot",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "crm.contact.search": {
        "handler": hubspot_connector.search_contacts,
        "tool_name": "hubspot.search_contacts",
        "description": "Search contacts in HubSpot CRM",
        "requires_oauth": True,
        "service": "hubspot",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    # ========== HUBSPOT DEALS ==========
    "crm.deal.create": {
        "handler": hubspot_connector.create_deal,
        "tool_name": "hubspot.create_deal",
        "description": "Create a deal in HubSpot CRM",
        "requires_oauth": True,
        "service": "hubspot",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "crm.deal.get": {
        "handler": hubspot_connector.get_deal,
        "tool_name": "hubspot.get_deal",
        "description": "Get deal details from HubSpot CRM",
        "requires_oauth": True,
        "service": "hubspot",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "crm.deal.list": {
        "handler": hubspot_connector.list_deals,
        "tool_name": "hubspot.list_deals",
        "description": "List deals from HubSpot CRM",
        "requires_oauth": True,
        "service": "hubspot",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "crm.deal.update": {
        "handler": hubspot_connector.update_deal,
        "tool_name": "hubspot.update_deal",
        "description": "Update a deal in HubSpot CRM",
        "requires_oauth": True,
        "service": "hubspot",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "crm.deal.delete": {
        "handler": hubspot_connector.delete_deal,
        "tool_name": "hubspot.delete_deal",
        "description": "Delete a deal from HubSpot CRM",
        "requires_oauth": True,
        "service": "hubspot",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "crm.deal.search": {
        "handler": hubspot_connector.search_deals,
        "tool_name": "hubspot.search_deals",
        "description": "Search deals in HubSpot CRM",
        "requires_oauth": True,
        "service": "hubspot",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    # ========== HUBSPOT COMPANIES ==========
    "crm.company.create": {
        "handler": hubspot_connector.create_company,
        "tool_name": "hubspot.create_company",
        "description": "Create a company in HubSpot CRM",
        "requires_oauth": True,
        "service": "hubspot",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "crm.company.get": {
        "handler": hubspot_connector.get_company,
        "tool_name": "hubspot.get_company",
        "description": "Get company details from HubSpot CRM",
        "requires_oauth": True,
        "service": "hubspot",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "crm.company.list": {
        "handler": hubspot_connector.list_companies,
        "tool_name": "hubspot.list_companies",
        "description": "List companies from HubSpot CRM",
        "requires_oauth": True,
        "service": "hubspot",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "crm.company.update": {
        "handler": hubspot_connector.update_company,
        "tool_name": "hubspot.update_company",
        "description": "Update a company in HubSpot CRM",
        "requires_oauth": True,
        "service": "hubspot",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "crm.company.delete": {
        "handler": hubspot_connector.delete_company,
        "tool_name": "hubspot.delete_company",
        "description": "Delete a company from HubSpot CRM",
        "requires_oauth": True,
        "service": "hubspot",
        "credential_type": "customer",
        "supports_delegation": False,
    },
    "crm.company.search": {
        "handler": hubspot_connector.search_companies,
        "tool_name": "hubspot.search_companies",
        "description": "Search companies in HubSpot CRM",
        "requires_oauth": True,
        "service": "hubspot",
        "credential_type": "customer",
        "supports_delegation": False,
    },
}
