"""
Monday.com Capability Registry
"""

from app.connectors.monday import MondayConnector

# Initialize connector
monday_connector = MondayConnector()

DELEGATION_INSTRUCTIONS = "Connect your Monday.com account to Aleq"

MONDAY_CAPABILITIES = {
    # ========== MONDAY.COM ==========
    "monday.board.list": {
        "handler": monday_connector.get_boards,
        "tool_name": "monday.get_boards",
        "description": "List boards in Monday.com workspace",
        "requires_oauth": True,
        "service": "monday",
        "credential_type": "customer",
        "supports_delegation": True,
        "delegation_instructions": DELEGATION_INSTRUCTIONS,
    },
    "monday.board.get": {
        "handler": monday_connector.get_board,
        "tool_name": "monday.get_board",
        "description": "Get board details from Monday.com with columns and groups",
        "requires_oauth": True,
        "service": "monday",
        "credential_type": "customer",
        "supports_delegation": True,
        "delegation_instructions": DELEGATION_INSTRUCTIONS,
    },
    "monday.item.create": {
        "handler": monday_connector.create_item,
        "tool_name": "monday.create_item",
        "description": "Create item on Monday.com board for finance workflows",
        "requires_oauth": True,
        "service": "monday",
        "credential_type": "customer",
        "supports_delegation": True,
        "delegation_instructions": DELEGATION_INSTRUCTIONS,
    },
    "monday.item.get": {
        "handler": monday_connector.get_item,
        "tool_name": "monday.get_item",
        "description": "Get item details from Monday.com",
        "requires_oauth": True,
        "service": "monday",
        "credential_type": "customer",
        "supports_delegation": True,
        "delegation_instructions": DELEGATION_INSTRUCTIONS,
    },
    "monday.item.list": {
        "handler": monday_connector.list_items,
        "tool_name": "monday.list_items",
        "description": "List items on Monday.com board with pagination",
        "requires_oauth": True,
        "service": "monday",
        "credential_type": "customer",
        "supports_delegation": True,
        "delegation_instructions": DELEGATION_INSTRUCTIONS,
    },
    "monday.item.update": {
        "handler": monday_connector.update_item,
        "tool_name": "monday.update_item",
        "description": "Update item name on Monday.com",
        "requires_oauth": True,
        "service": "monday",
        "credential_type": "customer",
        "supports_delegation": True,
        "delegation_instructions": DELEGATION_INSTRUCTIONS,
    },
    "monday.column.change_value": {
        "handler": monday_connector.change_column_value,
        "tool_name": "monday.change_column_value",
        "description": "Change single column value on Monday.com item (status, date, text)",
        "requires_oauth": True,
        "service": "monday",
        "credential_type": "customer",
        "supports_delegation": True,
        "delegation_instructions": DELEGATION_INSTRUCTIONS,
    },
    "monday.column.change_multiple_values": {
        "handler": monday_connector.change_multiple_column_values,
        "tool_name": "monday.change_multiple_column_values",
        "description": "Change multiple column values on Monday.com item at once",
        "requires_oauth": True,
        "service": "monday",
        "credential_type": "customer",
        "supports_delegation": True,
        "delegation_instructions": DELEGATION_INSTRUCTIONS,
    },
    "monday.update.create": {
        "handler": monday_connector.create_update,
        "tool_name": "monday.create_update",
        "description": "Create update (comment) on Monday.com item",
        "requires_oauth": True,
        "service": "monday",
        "credential_type": "customer",
        "supports_delegation": True,
        "delegation_instructions": DELEGATION_INSTRUCTIONS,
    },
    "monday.update.list": {
        "handler": monday_connector.get_item_updates,
        "tool_name": "monday.get_item_updates",
        "description": "Get all updates (comments) on Monday.com item",
        "requires_oauth": True,
        "service": "monday",
        "credential_type": "customer",
        "supports_delegation": True,
        "delegation_instructions": DELEGATION_INSTRUCTIONS,
    },
    "monday.user.list": {
        "handler": monday_connector.get_users,
        "tool_name": "monday.get_users",
        "description": "Get users in Monday.com account",
        "requires_oauth": True,
        "service": "monday",
        "credential_type": "customer",
        "supports_delegation": True,
        "delegation_instructions": DELEGATION_INSTRUCTIONS,
    },
    "monday.user.get_current": {
        "handler": monday_connector.get_current_user,
        "tool_name": "monday.get_current_user",
        "description": "Get current authenticated Monday.com user",
        "requires_oauth": True,
        "service": "monday",
        "credential_type": "customer",
        "supports_delegation": True,
        "delegation_instructions": DELEGATION_INSTRUCTIONS,
    },
    "monday.group.create": {
        "handler": monday_connector.create_group,
        "tool_name": "monday.create_group",
        "description": "Create group on Monday.com board",
        "requires_oauth": True,
        "service": "monday",
        "credential_type": "customer",
        "supports_delegation": True,
        "delegation_instructions": DELEGATION_INSTRUCTIONS,
    },
}
